export const ALL_GALLERY_PHOTOS = [
  // 🇮🇳 INDIA - NORTH & HIMALAYAS
  {
    filename: 'sonamarg-alpine-valley.jpg',
    title: 'Sonamarg Alpine Meadows & Glacial Streams',
    location: 'Sonamarg, Kashmir, India',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '2.4 MB',
  },
  {
    filename: 'taj-mahal-great-gate.jpg',
    title: 'Taj Mahal Through The Great Gate Archway',
    location: 'Agra, Uttar Pradesh, India',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.1 MB',
  },
  {
    filename: 'pahalgam-pine-valley.jpg',
    title: 'Pahalgam Pine Valley & Lidder River',
    location: 'Pahalgam, Kashmir, India',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '2.8 MB',
  },
  {
    filename: 'pangong-tso-ladakh.jpg',
    title: 'Pangong Tso Blue High Altitude Lake',
    location: 'Pangong Tso, Ladakh, India',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.5 MB',
  },
  {
    filename: 'hunder-desert-camels.jpg',
    title: 'Hunder Desert Sand Dunes & Bactrian Camels',
    location: 'Nubra Valley, Ladakh, India',
    category: 'Desert & Dunes',
    url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '2.6 MB',
  },
  {
    filename: 'spiti-key-gompa.jpg',
    title: 'Spiti Valley Key Gompa Mountain Monastery',
    location: 'Spiti Valley, Himachal Pradesh, India',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.2 MB',
  },
  {
    filename: 'solang-valley-pine.jpg',
    title: 'Solang Valley Alpine Pine Forests',
    location: 'Manali, Himachal Pradesh, India',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '2.9 MB',
  },
  {
    filename: 'rohtang-pass-snow.jpg',
    title: 'Himalayan Snow Peaks & Pine Ridge',
    location: 'Rohtang Pass, Himachal Pradesh, India',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.0 MB',
  },
  {
    filename: 'dhankar-lake-spiti.jpg',
    title: 'Dhankar High Altitude Lake & Mountain Reflections',
    location: 'Dhankar Lake, Spiti Valley, Himachal Pradesh, India',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.4 MB',
  },

  // 🇮🇳 INDIA - RAJASTHAN & HERITAGE
  {
    filename: 'hawa-mahal-facade.jpg',
    title: 'Hawa Mahal Palace of Winds Facade',
    location: 'Jaipur, Rajasthan, India',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.3 MB',
  },
  {
    filename: 'lake-pichola-city-palace.jpg',
    title: 'Lake Pichola City Palace Sunset View',
    location: 'Udaipur, Rajasthan, India',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '2.8 MB',
  },
  {
    filename: 'thar-desert-sam-dunes.jpg',
    title: 'Thar Desert Sam Sand Dunes at Sunset',
    location: 'Jaisalmer, Rajasthan, India',
    category: 'Desert & Dunes',
    url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.1 MB',
  },
  {
    filename: 'mehrangarh-fort-blue-city.jpg',
    title: 'Mehrangarh Fort Jodhpur Blue City View',
    location: 'Jodhpur, Rajasthan, India',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '2.7 MB',
  },
  {
    filename: 'taj-mahal-reflection-pool.jpg',
    title: 'Taj Mahal Front Reflection Pool',
    location: 'Agra, Uttar Pradesh, India',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.6 MB',
  },
  {
    filename: 'varanasi-ganga-aarti.jpg',
    title: 'Dashashwamedh Ghat Evening Ganga Aarti',
    location: 'Varanasi, Uttar Pradesh, India',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1561359313-0639aad49ca6?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '2.5 MB',
  },
  {
    filename: 'amer-fort-jaipur.jpg',
    title: 'Amer Fort Hilltop Palace & Ramparts',
    location: 'Jaipur, Rajasthan, India',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.2 MB',
  },
  {
    filename: 'golden-temple-amritsar.jpg',
    title: 'Harmandir Sahib Golden Temple Amrit Sarovar',
    location: 'Amritsar, Punjab, India',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.7 MB',
  },
  {
    filename: 'qutub-minar-delhi.jpg',
    title: 'Qutub Minar Red Sandstone Victory Tower',
    location: 'New Delhi, India',
    category: 'Heritage & Palaces',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Qutb_Minar_2022.jpg/1280px-Qutb_Minar_2022.jpg',
    fileType: 'Image',
    size: '2.9 MB',
  },
  {
    filename: 'hampi-stone-chariot.jpg',
    title: 'Hampi Vijayanagara Stone Chariot & Pillars',
    location: 'Hampi, Karnataka, India',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1600100397608-f010f443b2f9?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.5 MB',
  },

  // 🇮🇳 INDIA - KERALA, GOA, MEGHALAYA & SOUTH
  {
    filename: 'munnar-tea-gardens.jpg',
    title: 'Munnar Lush Green Tea Garden Hills',
    location: 'Munnar, Kerala, India',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.0 MB',
  },
  {
    filename: 'alleppey-houseboat.jpg',
    title: 'Alleppey Backwaters Traditional Houseboat',
    location: 'Alleppey, Kerala, India',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '2.7 MB',
  },
  {
    filename: 'varkala-cliff-beach.jpg',
    title: 'Varkala Beach Arabian Sea Red Cliffside',
    location: 'Varkala, Kerala, India',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.1 MB',
  },
  {
    filename: 'dawki-umngot-river.jpg',
    title: 'Dawki Umngot River Clear Waters',
    location: 'Dawki, Meghalaya, India',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '2.6 MB',
  },
  {
    filename: 'cherrapunji-root-bridge.jpg',
    title: 'Cherrapunji Rainforest Living Root Bridge',
    location: 'Cherrapunji, Meghalaya, India',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.4 MB',
  },
  {
    filename: 'havelock-radhanagar-beach.jpg',
    title: 'Havelock Radhanagar Tropical Beach',
    location: 'Havelock Island, Andamans, India',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.8 MB',
  },
  {
    filename: 'western-ghats-waterfalls.jpg',
    title: 'Western Ghats Sahyadri Monsoon Waterfalls',
    location: 'Mahabaleshwar, Maharashtra, India',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.2 MB',
  },

  // 🌍 INTERNATIONAL - MALDIVES & BALI
  {
    filename: 'maldives-overwater-lagoon.jpg',
    title: 'Maldives Overwater Resort Turquoise Lagoon',
    location: 'Baa Atoll, Maldives',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.1 MB',
  },
  {
    filename: 'maldives-sea-turtle-reef.jpg',
    title: 'Maldives Coral Reef Sea Turtle & Marine Life',
    location: 'Hanifaru Bay, Maldives',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1582967788606-a171c1080cb0?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.3 MB',
  },
  {
    filename: 'ubud-rice-terraces.jpg',
    title: 'Ubud Tegallalang Step Rice Terraces',
    location: 'Ubud, Bali, Indonesia',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.5 MB',
  },
  {
    filename: 'nusa-penida-kelingking.jpg',
    title: 'Nusa Penida Kelingking Coastal Cliff',
    location: 'Nusa Penida, Bali, Indonesia',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.7 MB',
  },
  {
    filename: 'uluwatu-sunset-temple.jpg',
    title: 'Uluwatu Sunset Temple over Sea Waves',
    location: 'Uluwatu, Bali, Indonesia',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.0 MB',
  },
  {
    filename: 'mount-batur-sunrise.jpg',
    title: 'Mount Batur Sunrise Caldera Volcano',
    location: 'Kintamani, Bali, Indonesia',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.6 MB',
  },

  // 🌍 INTERNATIONAL - MIDDLE EAST & EGYPT
  {
    filename: 'burj-khalifa-dubai-night.jpg',
    title: 'Burj Khalifa & Downtown Dubai Night Sky',
    location: 'Downtown Dubai, UAE',
    category: 'Urban & Skylines',
    url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.3 MB',
  },
  {
    filename: 'abu-dhabi-sand-dunes.jpg',
    title: 'Arabian Desert Golden Sand Dunes',
    location: 'Abu Dhabi Desert, UAE',
    category: 'Desert & Dunes',
    url: 'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '2.9 MB',
  },
  {
    filename: 'sheikh-zayed-grand-mosque.jpg',
    title: 'Sheikh Zayed Grand Mosque Marble Courtyard',
    location: 'Abu Dhabi, UAE',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.0 MB',
  },
  {
    filename: 'petra-treasury-jordan.jpg',
    title: 'Al-Khazneh Treasury Rock-Cut Temple',
    location: 'Petra, Jordan',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1579606032834-a82967664654?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.4 MB',
  },
  {
    filename: 'giza-pyramids-sunset.jpg',
    title: 'Great Pyramids of Giza & Desert Sunset',
    location: 'Giza, Cairo, Egypt',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.8 MB',
  },
  {
    filename: 'wadi-rum-mars-valley.jpg',
    title: 'Wadi Rum Desert Mars Valley Sandstone',
    location: 'Wadi Rum, Jordan',
    category: 'Desert & Dunes',
    url: 'https://images.unsplash.com/photo-1547234935-80c7145ec969?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.1 MB',
  },

  // 🌍 INTERNATIONAL - SWITZERLAND & EUROPE
  {
    filename: 'matterhorn-zermatt-lake.jpg',
    title: 'Matterhorn Alpine Peak Reflected in Lake',
    location: 'Zermatt, Switzerland',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.2 MB',
  },
  {
    filename: 'lauterbrunnen-valley-waterfalls.jpg',
    title: 'Lauterbrunnen Valley Staubbach Waterfalls',
    location: 'Lauterbrunnen, Bernese Oberland, Switzerland',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.9 MB',
  },
  {
    filename: 'grindelwald-cliffwalk.jpg',
    title: 'Grindelwald First Alpine Suspension Cliffwalk',
    location: 'Grindelwald, Switzerland',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1573155993874-d5d48af862ba?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.5 MB',
  },
  {
    filename: 'seceda-dolomites-ridgeline.jpg',
    title: 'Seceda Dolomite Ridgeline Sunrise Views',
    location: 'Val Gardena, Dolomites, Italy',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.4 MB',
  },
  {
    filename: 'lago-di-braies-boathouse.jpg',
    title: 'Lago di Braies Emerald Alpine Water & Boathouse',
    location: 'South Tyrol, Dolomites, Italy',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1508873535684-277a3cbcc4e8?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.1 MB',
  },
  {
    filename: 'eiffel-tower-sunset-seine.jpg',
    title: 'Eiffel Tower Sunset over Paris & River Seine',
    location: 'Paris, France',
    category: 'Urban & Skylines',
    url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.7 MB',
  },
  {
    filename: 'louvre-pyramid-night.jpg',
    title: 'Louvre Museum Glass Pyramid at Night',
    location: 'Paris, France',
    category: 'Urban & Skylines',
    url: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.6 MB',
  },
  {
    filename: 'positano-amalfi-pastel-village.jpg',
    title: 'Positano Amalfi Cliffside Pastel Houses',
    location: 'Positano, Amalfi Coast, Italy',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.9 MB',
  },
  {
    filename: 'venice-grand-canal-sunset.jpg',
    title: 'Venice Grand Canal Gondolas at Sunset',
    location: 'Venice, Italy',
    category: 'Urban & Skylines',
    url: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.8 MB',
  },
  {
    filename: 'colosseum-rome-twilight.jpg',
    title: 'Colosseum Roman Amphitheatre at Twilight',
    location: 'Rome, Italy',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.5 MB',
  },
  {
    filename: 'lake-como-bellagio-villas.jpg',
    title: 'Lake Como Bellagio Villa Coastal Vistas',
    location: 'Lake Como, Lombardy, Italy',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.3 MB',
  },

  // 🌍 INTERNATIONAL - JAPAN & ASIA
  {
    filename: 'mount-fuji-pagoda-blossoms.jpg',
    title: 'Mount Fuji & Chureito Pagoda in Spring Cherry Blossoms',
    location: 'Lake Kawaguchi, Yamanashi, Japan',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.5 MB',
  },
  {
    filename: 'arashiyama-bamboo-forest.jpg',
    title: 'Arashiyama Bamboo Forest Green Canopy',
    location: 'Kyoto, Japan',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.4 MB',
  },
  {
    filename: 'fushimi-inari-torii-path.jpg',
    title: 'Fushimi Inari Taisha Vermilion Torii Gate Path',
    location: 'Kyoto, Japan',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.6 MB',
  },
  {
    filename: 'shibuya-crossing-neon.jpg',
    title: 'Shibuya Crossing Tokyo Neon City Skyline',
    location: 'Tokyo, Japan',
    category: 'Urban & Skylines',
    url: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.7 MB',
  },
  {
    filename: 'halong-bay-limestone-karsts.jpg',
    title: 'Halong Bay Limestone Karsts & Emerald Sea',
    location: 'Halong Bay, Quang Ninh, Vietnam',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.8 MB',
  },
  {
    filename: 'maya-bay-phi-phi-turquoise.jpg',
    title: 'Maya Bay Phi Phi Leh Turquoise Waters',
    location: 'Krabi, Thailand',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.0 MB',
  },
  {
    filename: 'marina-bay-sands-singapore.jpg',
    title: 'Marina Bay Sands SkyPark & Singapore Skyline',
    location: 'Marina Bay, Singapore',
    category: 'Urban & Skylines',
    url: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.5 MB',
  },

  // 🌍 INTERNATIONAL - GREECE & TURKEY
  {
    filename: 'oia-santorini-blue-domes.jpg',
    title: 'Oia Santorini Whitewashed Blue Domes & Caldera',
    location: 'Oia, Santorini, Greece',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.2 MB',
  },
  {
    filename: 'navagio-shipwreck-beach.jpg',
    title: 'Navagio Shipwreck Beach Turquoise Bay',
    location: 'Zakynthos, Greece',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.9 MB',
  },
  {
    filename: 'cappadocia-hot-air-balloons.jpg',
    title: 'Cappadocia Sunrise Hot Air Balloons',
    location: 'Goreme, Cappadocia, Turkey',
    category: 'Desert & Dunes',
    url: 'https://images.unsplash.com/photo-1507608869274-d3177c8bb4c7?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.6 MB',
  },
  {
    filename: 'hagia-sophia-istanbul.jpg',
    title: 'Hagia Sophia Grand Mosque & Bosphorus Sunset',
    location: 'Sultanahmet, Istanbul, Turkey',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.4 MB',
  },

  // 🌍 INTERNATIONAL - OCEANIA, AFRICA & AMERICAS
  {
    filename: 'twelve-apostles-ocean-road.jpg',
    title: 'Twelve Apostles Great Ocean Road Coast',
    location: 'Great Ocean Road, Victoria, Australia',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.8 MB',
  },
  {
    filename: 'sydney-opera-house-harbour.jpg',
    title: 'Sydney Opera House & Harbour Bridge Reflection',
    location: 'Sydney Harbour, Australia',
    category: 'Urban & Skylines',
    url: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.7 MB',
  },
  {
    filename: 'table-mountain-cape-town.jpg',
    title: 'Table Mountain Coastal Landscape',
    location: 'Cape Town, South Africa',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.5 MB',
  },
  {
    filename: 'masai-mara-lion-pride.jpg',
    title: 'Masai Mara Savannah Lion Pride Wildlife Safari',
    location: 'Masai Mara National Reserve, Kenya',
    category: 'Desert & Dunes',
    url: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.0 MB',
  },
  {
    filename: 'banff-moraine-lake-alberta.jpg',
    title: 'Banff Moraine Lake Glacial Turquoise Water',
    location: 'Banff National Park, Alberta, Canada',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.3 MB',
  },
  {
    filename: 'machu-picchu-sacred-valley.jpg',
    title: 'Machu Picchu Incan Citadel in Morning Cloud Forest',
    location: 'Cusco, Sacred Valley, Peru',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.2 MB',
  },
  {
    filename: 'grand-canyon-south-rim.jpg',
    title: 'Grand Canyon South Rim Golden Sunset Layers',
    location: 'Arizona, United States',
    category: 'Desert & Dunes',
    url: 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.9 MB',
  },
  {
    filename: 'rio-christ-redeemer.jpg',
    title: 'Christ the Redeemer over Rio de Janeiro Bay',
    location: 'Rio de Janeiro, Brazil',
    category: 'Urban & Skylines',
    url: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.6 MB',
  },
  {
    filename: 'seychelles-pink-granite-beach.jpg',
    title: 'Anse Source d’Argent Pink Granite Beach',
    location: 'La Digue, Seychelles',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.1 MB',
  },
  {
    filename: 'mauritius-le-morne-lagoon.jpg',
    title: 'Le Morne Brabant Peninsula & Coastal Lagoon',
    location: 'Le Morne, Mauritius',
    category: 'Islands & Coastal',
    url: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.7 MB',
  },
  {
    filename: 'yosemite-el-capitan.jpg',
    title: 'Yosemite Valley El Capitan Granite Monolith',
    location: 'Yosemite, California, United States',
    category: 'Mountains & Alpine',
    url: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '4.0 MB',
  },
  {
    filename: 'dubrovnik-adriatic-walls.jpg',
    title: 'Dubrovnik Old Town Walls on the Adriatic Sea',
    location: 'Dubrovnik, Croatia',
    category: 'Heritage & Palaces',
    url: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80',
    fileType: 'Image',
    size: '3.8 MB',
  },
]
