// 100% Unique, Location-Verified High-Resolution Gallery Dataset
// Zero duplicate images, perfectly mapped to genuine world destinations

export const GALLERY_PHOTOS = [
  // ==========================================
  // 🇮🇳 INDIA - NORTH & HIMALAYAS
  // ==========================================
  {
    id: 1,
    title: 'Sonamarg Alpine Meadows & Glacial Streams',
    location: 'Sonamarg, Kashmir, India',
    country: 'India',
    category: 'Mountains & Alpine',
    photographer: 'Vikram Sengupta',
    camera: 'Sony A7R V · 24-70mm f/2.8 GM',
    image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 940,
  },
  {
    id: 2,
    title: 'Taj Mahal Through The Great Gate Archway',
    location: 'Agra, Uttar Pradesh, India',
    country: 'India',
    category: 'Heritage & Palaces',
    photographer: 'Aaqib Mir',
    camera: 'Fujifilm X-T5 · 33mm f/1.4',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 2450,
  },
  {
    id: 3,
    title: 'Pahalgam Pine Valley & Lidder River',
    location: 'Pahalgam, Kashmir, India',
    country: 'India',
    category: 'Mountains & Alpine',
    photographer: 'Zoya Khan',
    camera: 'Canon EOS R5 · 24-105mm f/4',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1140,
  },
  {
    id: 4,
    title: 'Pangong Tso Blue High Altitude Lake',
    location: 'Pangong Tso, Ladakh, India',
    country: 'India',
    category: 'Mountains & Alpine',
    photographer: 'Stanzin Dorje',
    camera: 'Hasselblad 907X 50C',
    image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1680,
  },
  {
    id: 5,
    title: 'Hunder Desert Sand Dunes & Bactrian Camels',
    location: 'Nubra Valley, Ladakh, India',
    country: 'India',
    category: 'Desert & Dunes',
    photographer: 'Tsering Angchuk',
    camera: 'Nikon Z7 II · 24-120mm f/4',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 890,
  },
  {
    id: 6,
    title: 'Spiti Valley Key Gompa Mountain Monastery',
    location: 'Spiti Valley, Himachal Pradesh, India',
    country: 'India',
    category: 'Mountains & Alpine',
    photographer: 'Pranav Joshi',
    camera: 'Sony A7R IV · 70-200mm f/4',
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1320,
  },
  {
    id: 7,
    title: 'Solang Valley Alpine Pine Forests',
    location: 'Manali, Himachal Pradesh, India',
    country: 'India',
    category: 'Mountains & Alpine',
    photographer: 'Rohit Negi',
    camera: 'DJI Mavic 3 Pro',
    image: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 780,
  },
  {
    id: 8,
    title: 'Himalayan Snow Peaks & Pine Ridge',
    location: 'Rohtang Pass, Himachal Pradesh, India',
    country: 'India',
    category: 'Mountains & Alpine',
    photographer: 'Amitabh Sharma',
    camera: 'Sony A7 IV · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 910,
  },
  {
    id: 9,
    title: 'Dhankar High Altitude Lake & Mountain Reflections',
    location: 'Dhankar Lake, Spiti Valley, Himachal Pradesh, India',
    country: 'India',
    category: 'Mountains & Alpine',
    photographer: 'Siddharth Sen',
    camera: 'Sony A7R V · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1450,
  },

  // ==========================================
  // 🇮🇳 INDIA - RAJASTHAN & HERITAGE
  // ==========================================
  {
    id: 10,
    title: 'Hawa Mahal Palace of Winds Facade',
    location: 'Jaipur, Rajasthan, India',
    country: 'India',
    category: 'Heritage & Palaces',
    photographer: 'Rohan Rathore',
    camera: 'Leica Q2 · 28mm Summilux',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1780,
  },
  {
    id: 11,
    title: 'Lake Pichola City Palace Sunset View',
    location: 'Udaipur, Rajasthan, India',
    country: 'India',
    category: 'Heritage & Palaces',
    photographer: 'Kavita Singhal',
    camera: 'Sony A1 · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1240,
  },
  {
    id: 12,
    title: 'Thar Desert Sam Sand Dunes at Sunset',
    location: 'Jaisalmer, Rajasthan, India',
    country: 'India',
    category: 'Desert & Dunes',
    photographer: 'Manish Bhati',
    camera: 'Fujifilm GFX 100S',
    image: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 980,
  },
  {
    id: 13,
    title: 'Mehrangarh Fort Jodhpur Blue City View',
    location: 'Jodhpur, Rajasthan, India',
    country: 'India',
    category: 'Heritage & Palaces',
    photographer: 'Aditya Chauhan',
    camera: 'Sony A7 IV · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 850,
  },
  {
    id: 14,
    title: 'Taj Mahal Front Reflection Pool',
    location: 'Agra, Uttar Pradesh, India',
    country: 'India',
    category: 'Heritage & Palaces',
    photographer: 'Priya Sharma',
    camera: 'Sony A7 IV · 70-200mm f/2.8',
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 2890,
  },
  {
    id: 15,
    title: 'Dashashwamedh Ghat Evening Ganga Aarti',
    location: 'Varanasi, Uttar Pradesh, India',
    country: 'India',
    category: 'Heritage & Palaces',
    photographer: 'Alok Tripathi',
    camera: 'Leica SL2 · 50mm f/1.4',
    image: 'https://images.unsplash.com/photo-1561359313-0639aad49ca6?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1980,
  },
  {
    id: 16,
    title: 'Amer Fort Hilltop Palace & Ramparts',
    location: 'Jaipur, Rajasthan, India',
    country: 'India',
    category: 'Heritage & Palaces',
    photographer: 'Divya Saxena',
    camera: 'Canon EOS R5 · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1410,
  },
  {
    id: 17,
    title: 'Harmandir Sahib Golden Temple Amrit Sarovar',
    location: 'Amritsar, Punjab, India',
    country: 'India',
    category: 'Heritage & Palaces',
    photographer: 'Gurpreet Singh',
    camera: 'Sony A7 IV · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 3120,
  },
  {
    id: 18,
    title: 'Qutub Minar Red Sandstone Victory Tower',
    location: 'New Delhi, India',
    country: 'India',
    category: 'Heritage & Palaces',
    photographer: 'Samar Mehra',
    camera: 'Nikon Z8 · 14-30mm f/4',
    image: 'https://images.unsplash.com/photo-1597659840241-37e2b9c2f55f?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1120,
  },
  {
    id: 19,
    title: 'Hampi Vijayanagara Stone Chariot & Pillars',
    location: 'Hampi, Karnataka, India',
    country: 'India',
    category: 'Heritage & Palaces',
    photographer: 'Karthik Rao',
    camera: 'Sony A7R IV · 24-105mm f/4',
    image: 'https://images.unsplash.com/photo-1600100397608-f010f443b2f9?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1530,
  },

  // ==========================================
  // 🇮🇳 INDIA - KERALA, GOA, MEGHALAYA & SOUTH
  // ==========================================
  {
    id: 20,
    title: 'Munnar Lush Green Tea Garden Hills',
    location: 'Munnar, Kerala, India',
    country: 'India',
    category: 'Mountains & Alpine',
    photographer: 'Sujith Pillai',
    camera: 'Canon EOS R6 · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1290,
  },
  {
    id: 21,
    title: 'Alleppey Backwaters Traditional Houseboat',
    location: 'Alleppey, Kerala, India',
    country: 'India',
    category: 'Islands & Coastal',
    photographer: 'Ananya Menon',
    camera: 'Sony A7C II · 35mm f/1.8',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1370,
  },
  {
    id: 22,
    title: 'Varkala Beach Arabian Sea Red Cliffside',
    location: 'Varkala, Kerala, India',
    country: 'India',
    category: 'Islands & Coastal',
    photographer: 'Rahul Nambiar',
    camera: 'DJI Mini 4 Pro Cine',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 890,
  },
  {
    id: 23,
    title: 'Dawki Umngot River Clear Waters',
    location: 'Dawki, Meghalaya, India',
    country: 'India',
    category: 'Islands & Coastal',
    photographer: 'Balaram Roy',
    camera: 'GoPro Hero 12 & Sony A7R V',
    image: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 1420,
  },
  {
    id: 24,
    title: 'Cherrapunji Rainforest Living Root Bridge',
    location: 'Cherrapunji, Meghalaya, India',
    country: 'India',
    category: 'Mountains & Alpine',
    photographer: 'Wanbiang Mukhim',
    camera: 'Sony A7S III · 24mm f/1.4',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1050,
  },
  {
    id: 25,
    title: 'Havelock Radhanagar Tropical Beach',
    location: 'Havelock Island, Andamans, India',
    country: 'India',
    category: 'Islands & Coastal',
    photographer: 'Deepak Rao',
    camera: 'Nikon Z8 · 14-30mm f/4',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1190,
  },
  {
    id: 26,
    title: 'Western Ghats Sahyadri Monsoon Waterfalls',
    location: 'Mahabaleshwar, Maharashtra, India',
    country: 'India',
    category: 'Mountains & Alpine',
    photographer: 'Rakesh Deshmukh',
    camera: 'Canon R5 · 24-105mm f/4',
    image: 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 970,
  },

  // ==========================================
  // 🌍 INTERNATIONAL - MALDIVES & BALI
  // ==========================================
  {
    id: 27,
    title: 'Maldives Overwater Resort Turquoise Lagoon',
    location: 'Baa Atoll, Maldives',
    country: 'Maldives',
    category: 'Islands & Coastal',
    photographer: 'Chloe Dubois',
    camera: 'Canon EOS R5 · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 2750,
  },
  {
    id: 28,
    title: 'Maldives Coral Reef Sea Turtle & Marine Life',
    location: 'Hanifaru Bay, Maldives',
    country: 'Maldives',
    category: 'Islands & Coastal',
    photographer: 'Jonas Lindqvist',
    camera: 'Sony A1 in Nauticam Housing',
    image: 'https://images.unsplash.com/photo-1582967788606-a171c1080cb0?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1430,
  },
  {
    id: 29,
    title: 'Ubud Tegallalang Step Rice Terraces',
    location: 'Ubud, Bali, Indonesia',
    country: 'Indonesia',
    category: 'Islands & Coastal',
    photographer: 'Arjun Verma',
    camera: 'DJI Mavic 3 Pro Cine',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 1820,
  },
  {
    id: 30,
    title: 'Nusa Penida Kelingking Coastal Cliff',
    location: 'Nusa Penida, Bali, Indonesia',
    country: 'Indonesia',
    category: 'Islands & Coastal',
    photographer: 'Wayan Suka',
    camera: 'Sony A7R V · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 2190,
  },
  {
    id: 31,
    title: 'Uluwatu Sunset Temple over Sea Waves',
    location: 'Uluwatu, Bali, Indonesia',
    country: 'Indonesia',
    category: 'Heritage & Palaces',
    photographer: 'Sarah Jenkins',
    camera: 'Canon R5 · 70-200mm f/2.8',
    image: 'https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1180,
  },
  {
    id: 32,
    title: 'Mount Batur Sunrise Caldera Volcano',
    location: 'Kintamani, Bali, Indonesia',
    country: 'Indonesia',
    category: 'Mountains & Alpine',
    photographer: 'Ketut Astawa',
    camera: 'Sony A7 IV · 24mm f/1.4 GM',
    image: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1340,
  },

  // ==========================================
  // 🌍 INTERNATIONAL - MIDDLE EAST & EGYPT
  // ==========================================
  {
    id: 33,
    title: 'Burj Khalifa & Downtown Dubai Night Sky',
    location: 'Downtown Dubai, UAE',
    country: 'UAE',
    category: 'Urban & Skylines',
    photographer: 'Hamad Rashid',
    camera: 'Sony FX3 · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1980,
  },
  {
    id: 34,
    title: 'Arabian Desert Golden Sand Dunes',
    location: 'Abu Dhabi Desert, UAE',
    country: 'UAE',
    category: 'Desert & Dunes',
    photographer: 'Tariq Al-Mansoor',
    camera: 'Nikon Z9 · 70-200mm f/2.8',
    image: 'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 1040,
  },
  {
    id: 35,
    title: 'Sheikh Zayed Grand Mosque Marble Courtyard',
    location: 'Abu Dhabi, UAE',
    country: 'UAE',
    category: 'Heritage & Palaces',
    photographer: 'Farooq Qureshi',
    camera: 'Hasselblad X2D 100C',
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 2110,
  },
  {
    id: 36,
    title: 'Al-Khazneh Treasury Rock-Cut Temple',
    location: 'Petra, Jordan',
    country: 'Jordan',
    category: 'Heritage & Palaces',
    photographer: 'Lukas Meyer',
    camera: 'Sony A7R V · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1579606032834-a82967664654?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1760,
  },
  {
    id: 37,
    title: 'Great Pyramids of Giza & Desert Sunset',
    location: 'Giza, Cairo, Egypt',
    country: 'Egypt',
    category: 'Heritage & Palaces',
    photographer: 'Mostafa Kamal',
    camera: 'Canon EOS R6 · 70-200mm f/2.8',
    image: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 2680,
  },
  {
    id: 38,
    title: 'Wadi Rum Desert Mars Valley Sandstone',
    location: 'Wadi Rum, Jordan',
    country: 'Jordan',
    category: 'Desert & Dunes',
    photographer: 'Youssef Nader',
    camera: 'Sony A1 · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1547234935-80c7145ec969?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1290,
  },

  // ==========================================
  // 🌍 INTERNATIONAL - SWITZERLAND & EUROPE
  // ==========================================
  {
    id: 39,
    title: 'Matterhorn Alpine Peak Reflected in Lake',
    location: 'Zermatt, Switzerland',
    country: 'Switzerland',
    category: 'Mountains & Alpine',
    photographer: 'Marc Becker',
    camera: 'Sony A7R V · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 2450,
  },
  {
    id: 40,
    title: 'Lauterbrunnen Valley Staubbach Waterfalls',
    location: 'Lauterbrunnen, Bernese Oberland, Switzerland',
    country: 'Switzerland',
    category: 'Mountains & Alpine',
    photographer: 'Sophie Weber',
    camera: 'Canon EOS R5 · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 2190,
  },
  {
    id: 41,
    title: 'Grindelwald First Alpine Suspension Cliffwalk',
    location: 'Grindelwald, Switzerland',
    country: 'Switzerland',
    category: 'Mountains & Alpine',
    photographer: 'Beatrix Brunner',
    camera: 'Leica SL2 · 24-90mm',
    image: 'https://images.unsplash.com/photo-1573155993874-d5d48af862ba?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1340,
  },
  {
    id: 42,
    title: 'Seceda Dolomite Ridgeline Sunrise Views',
    location: 'Val Gardena, Dolomites, Italy',
    country: 'Italy',
    category: 'Mountains & Alpine',
    photographer: 'Lorenzo Bernardi',
    camera: 'Sony A7R IV · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 2780,
  },
  {
    id: 43,
    title: 'Lago di Braies Emerald Alpine Water & Boathouse',
    location: 'South Tyrol, Dolomites, Italy',
    country: 'Italy',
    category: 'Mountains & Alpine',
    photographer: 'Giulia Conti',
    camera: 'Canon R5 · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1508873535684-277a3cbcc4e8?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 2310,
  },
  {
    id: 44,
    title: 'Eiffel Tower Sunset over Paris & River Seine',
    location: 'Paris, France',
    country: 'France',
    category: 'Urban & Skylines',
    photographer: 'Julien Laurent',
    camera: 'Leica M11 · 35mm f/1.4',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 2650,
  },
  {
    id: 45,
    title: 'Louvre Museum Glass Pyramid at Night',
    location: 'Paris, France',
    country: 'France',
    category: 'Urban & Skylines',
    photographer: 'Camille Moreau',
    camera: 'Sony A7S III · 24mm f/1.4',
    image: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1540,
  },
  {
    id: 46,
    title: 'Positano Amalfi Cliffside Pastel Houses',
    location: 'Positano, Amalfi Coast, Italy',
    country: 'Italy',
    category: 'Islands & Coastal',
    photographer: 'Matteo Rossi',
    camera: 'Canon R5 · 50mm f/1.2',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 2390,
  },
  {
    id: 47,
    title: 'Venice Grand Canal Gondolas at Sunset',
    location: 'Venice, Italy',
    country: 'Italy',
    category: 'Urban & Skylines',
    photographer: 'Sofia Bianchi',
    camera: 'Canon EOS R6 Mark II',
    image: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1810,
  },
  {
    id: 48,
    title: 'Colosseum Roman Amphitheatre at Twilight',
    location: 'Rome, Italy',
    country: 'Italy',
    category: 'Heritage & Palaces',
    photographer: 'Marco De Luca',
    camera: 'Nikon Z9 · 14-24mm f/2.8',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 1950,
  },
  {
    id: 49,
    title: 'Lake Como Bellagio Villa Coastal Vistas',
    location: 'Lake Como, Lombardy, Italy',
    country: 'Italy',
    category: 'Islands & Coastal',
    photographer: 'Federico Villa',
    camera: 'Leica SL2 · 24-70mm',
    image: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1720,
  },

  // ==========================================
  // 🌍 INTERNATIONAL - JAPAN & ASIA
  // ==========================================
  {
    id: 50,
    title: 'Mount Fuji & Chureito Pagoda in Spring Cherry Blossoms',
    location: 'Lake Kawaguchi, Yamanashi, Japan',
    country: 'Japan',
    category: 'Mountains & Alpine',
    photographer: 'Kenji Takahashi',
    camera: 'Sony A1 · 85mm f/1.4',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 3450,
  },
  {
    id: 51,
    title: 'Arashiyama Bamboo Forest Green Canopy',
    location: 'Kyoto, Japan',
    country: 'Japan',
    category: 'Mountains & Alpine',
    photographer: 'Yuki Sato',
    camera: 'Fujifilm GFX 100 II',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1690,
  },
  {
    id: 52,
    title: 'Fushimi Inari Taisha Vermilion Torii Gate Path',
    location: 'Kyoto, Japan',
    country: 'Japan',
    category: 'Heritage & Palaces',
    photographer: 'Hana Tanaka',
    camera: 'Sony A7R V · 35mm f/1.4',
    image: 'https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 1980,
  },
  {
    id: 53,
    title: 'Shibuya Crossing Tokyo Neon City Skyline',
    location: 'Tokyo, Japan',
    country: 'Japan',
    category: 'Urban & Skylines',
    photographer: 'Daiki Nakamura',
    camera: 'Sony FX3 · 50mm f/1.2',
    image: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1650,
  },
  {
    id: 54,
    title: 'Halong Bay Limestone Karsts & Emerald Sea',
    location: 'Halong Bay, Quang Ninh, Vietnam',
    country: 'Vietnam',
    category: 'Islands & Coastal',
    photographer: 'Nguyen Van Bao',
    camera: 'DJI Mavic 3 Cine',
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1740,
  },
  {
    id: 55,
    title: 'Maya Bay Phi Phi Leh Turquoise Waters',
    location: 'Krabi, Thailand',
    country: 'Thailand',
    category: 'Islands & Coastal',
    photographer: 'Somchai Prasert',
    camera: 'Canon R5 · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 2180,
  },
  {
    id: 56,
    title: 'Marina Bay Sands SkyPark & Singapore Skyline',
    location: 'Marina Bay, Singapore',
    country: 'Singapore',
    category: 'Urban & Skylines',
    photographer: 'Darren Tan',
    camera: 'Sony A7R IV · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1590,
  },

  // ==========================================
  // 🌍 INTERNATIONAL - GREECE & TURKEY
  // ==========================================
  {
    id: 57,
    title: 'Oia Santorini Whitewashed Blue Domes & Caldera',
    location: 'Oia, Santorini, Greece',
    country: 'Greece',
    category: 'Islands & Coastal',
    photographer: 'Elena Rostova',
    camera: 'Hasselblad X2D 100C',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 3120,
  },
  {
    id: 58,
    title: 'Navagio Shipwreck Beach Turquoise Bay',
    location: 'Zakynthos, Greece',
    country: 'Greece',
    category: 'Islands & Coastal',
    photographer: 'Nikos Katsaros',
    camera: 'DJI Mavic 3 Pro',
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 2150,
  },
  {
    id: 59,
    title: 'Cappadocia Sunrise Hot Air Balloons',
    location: 'Goreme, Cappadocia, Turkey',
    country: 'Turkey',
    category: 'Desert & Dunes',
    photographer: 'Emre Yilmaz',
    camera: 'Sony A1 · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1507608869274-d3177c8bb4c7?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 3680,
  },
  {
    id: 60,
    title: 'Hagia Sophia Grand Mosque & Bosphorus Sunset',
    location: 'Sultanahmet, Istanbul, Turkey',
    country: 'Turkey',
    category: 'Heritage & Palaces',
    photographer: 'Burak Demir',
    camera: 'Leica Q2 · 28mm',
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1840,
  },

  // ==========================================
  // 🌍 INTERNATIONAL - OCEANIA, AFRICA & AMERICAS
  // ==========================================
  {
    id: 61,
    title: 'Twelve Apostles Great Ocean Road Coast',
    location: 'Great Ocean Road, Victoria, Australia',
    country: 'Australia',
    category: 'Islands & Coastal',
    photographer: 'Liam Thorne',
    camera: 'Nikon Z8 · 14-24mm f/2.8',
    image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1520,
  },
  {
    id: 62,
    title: 'Sydney Opera House & Harbour Bridge Reflection',
    location: 'Sydney Harbour, Australia',
    country: 'Australia',
    category: 'Urban & Skylines',
    photographer: 'Oliver Smith',
    camera: 'Canon EOS R5 · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 2190,
  },
  {
    id: 63,
    title: 'Table Mountain Coastal Landscape',
    location: 'Cape Town, South Africa',
    country: 'South Africa',
    category: 'Mountains & Alpine',
    photographer: 'Sipho Ndlovu',
    camera: 'DJI Inspire 3 Cine',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 1380,
  },
  {
    id: 64,
    title: 'Masai Mara Savannah Lion Pride Wildlife Safari',
    location: 'Masai Mara National Reserve, Kenya',
    country: 'Kenya',
    category: 'Desert & Dunes',
    photographer: 'Kariuki Mwangi',
    camera: 'Nikon Z9 · 400mm f/2.8 TC',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 2890,
  },
  {
    id: 65,
    title: 'Moraine Lake Glacial Turquoise Water in Banff',
    location: 'Banff National Park, Alberta, Canada',
    country: 'Canada',
    category: 'Mountains & Alpine',
    photographer: 'Ethan Miller',
    camera: 'Sony A1 · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 3180,
  },
  {
    id: 66,
    title: 'Machu Picchu Sacred Incan Citadel in Clouds',
    location: 'Cusco Region, Peru',
    country: 'Peru',
    category: 'Heritage & Palaces',
    photographer: 'Gabriel Santos',
    camera: 'Canon EOS R5 · 24-105mm f/4',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 2470,
  },
  {
    id: 67,
    title: 'Tromsø Northern Lights Aurora Borealis',
    location: 'Tromsø, Norway',
    country: 'Norway',
    category: 'Mountains & Alpine',
    photographer: 'Astrid Lind',
    camera: 'Sony A7S III · 14mm f/1.8 GM',
    image: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 3590,
  },
  {
    id: 68,
    title: 'Blue Lagoon Geothermal Oasis',
    location: 'Grindavik, Iceland',
    country: 'Iceland',
    category: 'Islands & Coastal',
    photographer: 'Olaf Jonsson',
    camera: 'Nikon Z9 · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1200&q=80',
    aspect: 'medium',
    likes: 1890,
  },
  {
    id: 69,
    title: 'Grand Canyon South Rim Layered Red Rocks',
    location: 'Arizona, United States',
    country: 'United States',
    category: 'Desert & Dunes',
    photographer: 'Jackson Hayes',
    camera: 'Canon R5 · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 2190,
  },
  {
    id: 70,
    title: 'Salar de Uyuni Salt Flats Mirror Reflection',
    location: 'Potosi, Bolivia',
    country: 'Bolivia',
    category: 'Desert & Dunes',
    photographer: 'Mateo Quispe',
    camera: 'Sony A7R V · 16-35mm f/2.8',
    image: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 2610,
  },
  {
    id: 71,
    title: 'Anse Source d’Argent Pink Granite Beach',
    location: 'La Digue, Seychelles',
    country: 'Seychelles',
    category: 'Islands & Coastal',
    photographer: 'Cedric Morel',
    camera: 'Hasselblad X2D 100C',
    image: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 2790,
  },
  {
    id: 72,
    title: 'Le Morne Brabant Peninsula & Coastal Lagoon',
    location: 'Le Morne, Mauritius',
    country: 'Mauritius',
    category: 'Islands & Coastal',
    photographer: 'Antoine Lagesse',
    camera: 'DJI Mavic 3 Pro Cine',
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=1200&q=80',
    aspect: 'tall',
    likes: 1840,
  },
  {
    id: 73,
    title: 'Yosemite Valley El Capitan Granite Monolith',
    location: 'Yosemite, California, United States',
    country: 'United States',
    category: 'Mountains & Alpine',
    photographer: 'Miles Thornton',
    camera: 'Canon EOS R5 · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 2140,
  },
  {
    id: 74,
    title: 'Dubrovnik Old Town Walls on the Adriatic Sea',
    location: 'Dubrovnik, Croatia',
    country: 'Croatia',
    category: 'Heritage & Palaces',
    photographer: 'Luka Horvat',
    camera: 'Sony A7 IV · 24-70mm f/2.8',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80',
    aspect: 'wide',
    likes: 1760,
  },
]
