// Curated high-resolution cinematic mock dataset for Tours & Travels

export const DESTINATIONS = [
  {
    id: 'kashmir',
    slug: 'kashmir',
    name: 'Kashmir',
    country: 'India',
    region: 'Asia',
    tagline: 'Paradise on Earth',
    description: 'Immerse yourself in alpine valleys, pristine Dal Lake shikara rides, snow-capped Himalayan peaks, and serene pine forests.',
    image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 12,
    startingPrice: 24999,
    rating: 4.9,
    highlights: ['Gulmarg Gondola Ride', 'Dal Lake Houseboat Stay', 'Pahalgam Valley Trek', 'Sonamarg Glaciers'],
    weather: '12°C - 22°C (Optimal Spring/Autumn)',
    bestTime: 'April to October',
  },
  {
    id: 'maldives',
    slug: 'maldives',
    name: 'Maldives',
    country: 'Indian Ocean',
    region: 'Islands',
    tagline: 'Turquoise Seclusion & Coral Reefs',
    description: 'Private overwater bungalows, crystal clear lagoons, bioluminescent beaches, and unmatched underwater marine life.',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1400&q=85',
    aspect: 'wide',
    toursCount: 18,
    startingPrice: 84999,
    rating: 5.0,
    highlights: ['Private Overwater Villa', 'Manta Ray & Whale Shark Diving', 'Sunset Yacht Cruise', 'Sandbank Picnics'],
    weather: '27°C - 31°C (Tropical Warmth)',
    bestTime: 'November to April',
  },
  {
    id: 'bali',
    slug: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Islands',
    tagline: 'Island of Gods & Verdant Terraces',
    description: 'Ancient cliffside temples, sacred emerald rice terraces in Ubud, volcanic sunrises, and spiritual wellness sanctuaries.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=85',
    aspect: 'medium',
    toursCount: 24,
    startingPrice: 38999,
    rating: 4.9,
    highlights: ['Ubud Jungle Retreat', 'Mount Batur Sunrise Trek', 'Uluwatu Sunset Temple', 'Nusa Penida Expedition'],
    weather: '26°C - 30°C (Sunny/Breezy)',
    bestTime: 'May to September',
  },
  {
    id: 'rajasthan',
    slug: 'rajasthan',
    name: 'Rajasthan',
    country: 'India',
    region: 'Asia',
    tagline: 'Royal Fortresses & Golden Sands',
    description: 'Majestic Rajput palaces, Thar Desert stargazing under silk tents, vibrant heritage havelis, and royal dining.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1400&q=85',
    aspect: 'wide',
    toursCount: 15,
    startingPrice: 18999,
    rating: 4.9,
    highlights: ['Udaipur Lake Palace Experience', 'Jaisalmer Desert Safari', 'Jaipur Royal Amber Fort', 'Ranthambore Tiger Safari'],
    weather: '18°C - 28°C (Pleasant Winter)',
    bestTime: 'October to March',
  },
  {
    id: 'dubai',
    slug: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    region: 'Middle East',
    tagline: 'Futuristic Luxury & Arabian Glamour',
    description: 'Iconic architectural marvels, ultra-luxury shopping, desert dune luxury glamping, and world-class culinary dining.',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 20,
    startingPrice: 48999,
    rating: 4.8,
    highlights: ['Burj Khalifa Sky Deck', 'Private Desert Falconry & Dining', 'Palm Jumeirah Yachting', 'Old Dubai Spice Souks'],
    weather: '24°C - 32°C (Clear Skies)',
    bestTime: 'November to March',
  },
  {
    id: 'paris',
    slug: 'paris',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    tagline: 'City of Romance, Art & Haute Cuisine',
    description: 'Stroll along the Seine, explore world-renowned art galleries, taste Michelin-star gastronomy, and savor Parisian elegance.',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=85',
    aspect: 'small',
    toursCount: 16,
    startingPrice: 124999,
    rating: 4.9,
    highlights: ['Private Louvre After-Hours Tour', 'Seine River Gourmet Cruise', 'Montmartre Atelier Walks', 'Versailles Palace Gardens'],
    weather: '14°C - 23°C (Gentle Spring/Summer)',
    bestTime: 'April to October',
  },
  {
    id: 'switzerland',
    slug: 'switzerland',
    name: 'Switzerland',
    country: 'Europe',
    region: 'Europe',
    tagline: 'Alpine Wonder & Crystal Glaciers',
    description: 'Breathtaking peaks of the Matterhorn, panoramic Glacier Express trains, lakeside Swiss chalets, and pristine alpine meadows.',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 14,
    startingPrice: 149999,
    rating: 5.0,
    highlights: ['Glacier Express First Class', 'Matterhorn Sunrise Trek', 'Lake Geneva Private Cruise', 'Interlaken Heli-Tour'],
    weather: '10°C - 20°C (Alpine Fresh)',
    bestTime: 'June to October',
  },
  {
    id: 'tokyo',
    slug: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    tagline: 'Neon Metropolis & Zen Temples',
    description: 'Immersive blend of futuristic neon districts, ancient Shinto shrines, Michelin omakase dining, and serene bamboo groves.',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=85',
    aspect: 'medium',
    toursCount: 22,
    startingPrice: 134999,
    rating: 4.9,
    highlights: ['Shibuya Crossing Sky Deck', 'Private Tea Ceremony Kyoto', 'Mount Fuji Day Tour', 'Ginza High-End Dining'],
    weather: '15°C - 25°C (Cherry Blossom / Autumn)',
    bestTime: 'March to May, Sept to Nov',
  },
  {
    id: 'santorini',
    slug: 'santorini',
    name: 'Santorini',
    country: 'Greece',
    region: 'Europe',
    tagline: 'Aegean Sunsets & Caldera Cliffs',
    description: 'Iconic blue-domed churches, cliffside cave suites with infinity plunge pools overlooking the Aegean Sea, and volcanic wine tasting.',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=85',
    aspect: 'wide',
    toursCount: 11,
    startingPrice: 119999,
    rating: 4.9,
    highlights: ['Oia Sunset Catamaran Cruise', 'Volcanic Wineries Tasting', 'Private Caldera Helicopter Flight', 'Akrotiri Ruins'],
    weather: '22°C - 28°C (Mediterranean Breeze)',
    bestTime: 'May to October',
  },
  {
    id: 'amalfi',
    slug: 'amalfi-coast',
    name: 'Amalfi Coast',
    country: 'Italy',
    region: 'Europe',
    tagline: 'Cliffside Glamour & Tyrrhenian Waves',
    description: 'Pastel cliffside villages of Positano and Ravello, cliff-edge lemon groves, private speedboats to Capri, and vintage coastal drives.',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 13,
    startingPrice: 139999,
    rating: 4.9,
    highlights: ['Private Capri Island Charter', 'Ravello Villa Gardens', 'Positano Sunset Dining', 'Limoncello Artisan Masterclass'],
    weather: '20°C - 27°C (Sunny Coastal)',
    bestTime: 'May to September',
  },
  {
    id: 'kyoto',
    slug: 'kyoto',
    name: 'Kyoto',
    country: 'Japan',
    region: 'Asia',
    tagline: 'Imperial Shrines & Bamboo Sanctuaries',
    description: 'Walk through thousands of scarlet Torii gates at Fushimi Inari, serene Zen moss gardens, and historic Geisha tea houses.',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=85',
    aspect: 'medium',
    toursCount: 16,
    startingPrice: 129999,
    rating: 5.0,
    highlights: ['Arashiyama Bamboo Forest', 'Fushimi Inari Private Tour', 'Kinkaku-ji Golden Pavilion', 'Artisan Matcha Masterclass'],
    weather: '14°C - 24°C (Cherry Blossom/Autumn)',
    bestTime: 'March to May & Oct to Nov',
  },
  {
    id: 'ladakh',
    slug: 'ladakh',
    name: 'Ladakh',
    country: 'India',
    region: 'Asia',
    tagline: 'Land of High Passes & Azure Lakes',
    description: 'Pristine blue waters of Pangong Tso, dramatic lunar landscapes of Nubra Valley, and centuries-old clifftop Tibetan gompas.',
    image: 'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 15,
    startingPrice: 32999,
    rating: 4.9,
    highlights: ['Pangong Tso Stargazing Glamping', 'Nubra Valley Camel Safari', 'Khardung La High Pass', 'Thiksey Monastery Sunrise'],
    weather: '10°C - 20°C (Crisp Mountain Summer)',
    bestTime: 'May to September',
  },
  {
    id: 'iceland',
    slug: 'iceland',
    name: 'Iceland',
    country: 'Nordic Europe',
    region: 'Europe',
    tagline: 'Land of Fire, Ice & Northern Lights',
    description: 'Emerald Aurora Borealis dancing over snowfields, geothermal Blue Lagoon pools, erupting geysers, and massive crystalline ice caves.',
    image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1200&q=85',
    aspect: 'wide',
    toursCount: 12,
    startingPrice: 174999,
    rating: 5.0,
    highlights: ['Northern Lights Private Chase', 'Blue Lagoon Geothermal Retreat', 'Golden Circle Super-Jeep', 'Vatnajökull Glacier Hike'],
    weather: '-2°C to 12°C (Sub-Arctic Magic)',
    bestTime: 'Sept to March (Aurora) / June to Aug',
  },
  {
    id: 'rome',
    slug: 'rome',
    name: 'Rome',
    country: 'Italy',
    region: 'Europe',
    tagline: 'The Eternal City of Empires & Art',
    description: 'Private after-hours tours of the Colosseum and Vatican Museums, baroque fountains, and candlelit Michelin culinary alleys in Trastevere.',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=85',
    aspect: 'medium',
    toursCount: 19,
    startingPrice: 114999,
    rating: 4.8,
    highlights: ['VIP Colosseum Underground Access', 'Vatican Museums Private Curatorship', 'Trastevere Gourmet Tasting', 'Borghese Gallery'],
    weather: '16°C - 28°C (Pleasant Mediterranean)',
    bestTime: 'April to June & Sept to Nov',
  },
  {
    id: 'london',
    slug: 'london',
    name: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    tagline: 'Royal Palaces & Historic Grandeur',
    description: 'Private Thames river charters, historic Tower of London Crown Jewels, West End theatre private boxes, and luxury Mayfair shopping.',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 17,
    startingPrice: 129999,
    rating: 4.8,
    highlights: ['Tower of London Private Access', 'Buckingham Palace State Rooms', 'Thames Champagne Yacht', 'Windsor Castle Private Tour'],
    weather: '13°C - 22°C (Mild British Summer)',
    bestTime: 'May to September',
  },
  {
    id: 'newyork',
    slug: 'new-york',
    name: 'New York City',
    country: 'USA',
    region: 'Americas',
    tagline: 'The Iconic Capital of the World',
    description: 'Helicopter skyline tours over Manhattan, private Broadway backstage access, Michelin-star dining, and Central Park luxury horse carriages.',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 21,
    startingPrice: 159999,
    rating: 4.9,
    highlights: ['Manhattan Skyline Helicopter Flight', 'Summit One Vanderbilt VIP', 'Metropolitan Museum Private Tour', 'Broadway VIP Lounge'],
    weather: '15°C - 26°C (Vibrant Autumn/Spring)',
    bestTime: 'September to December & April to June',
  },
  {
    id: 'capetown',
    slug: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    region: 'Africa',
    tagline: 'Atlantic Oceans, Table Mountain & Vineyards',
    description: 'Ascend Table Mountain cableway, meet Boulders Beach wild penguins, helicopter over Cape Point, and sip world-class Stellenbosch vintages.',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=85',
    aspect: 'wide',
    toursCount: 14,
    startingPrice: 119999,
    rating: 4.9,
    highlights: ['Table Mountain Sunset Cableway', 'Cape Peninsula & Boulders Penguins', 'Stellenbosch Private Wine Estate', 'Shark Cage Diving'],
    weather: '18°C - 27°C (Sunny Mediterranean Climate)',
    bestTime: 'November to April',
  },
  {
    id: 'borabora',
    slug: 'bora-bora',
    name: 'Bora Bora',
    country: 'French Polynesia',
    region: 'Islands',
    tagline: 'The Pearl of the Pacific & Emerald Peak',
    description: 'Overwater bungalows over turquoise crystal lagoons, dramatic basalt peaks of Mount Otemanu, and private ray feeding experiences.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85',
    aspect: 'wide',
    toursCount: 10,
    startingPrice: 219999,
    rating: 5.0,
    highlights: ['Mount Otemanu Helicopter Flight', 'Lagoon Shark & Ray Safari', 'Private Motu Island Champagne Picnic', 'Polynesian Spa Ritual'],
    weather: '26°C - 30°C (South Pacific Warmth)',
    bestTime: 'May to October',
  },
  {
    id: 'phuket',
    slug: 'phuket',
    name: 'Phuket & Phi Phi',
    country: 'Thailand',
    region: 'Islands',
    tagline: 'Emerald Andaman Seas & Limestone Pinnacles',
    description: 'Speedboat through dramatic James Bond limestone karst towers, private pool villas in secluded bays, and vibrant Thai culinary culture.',
    image: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=1200&q=85',
    aspect: 'medium',
    toursCount: 20,
    startingPrice: 34999,
    rating: 4.8,
    highlights: ['Phi Phi Islands Private Speedboat', 'Phang Nga Bay Sunset Kayak', 'Luxury Clifftop Pool Villa', 'Elephant Sanctuary Visit'],
    weather: '27°C - 32°C (Warm Tropical)',
    bestTime: 'November to April',
  },
  {
    id: 'cairo',
    slug: 'cairo',
    name: 'Cairo & Giza',
    country: 'Egypt',
    region: 'Middle East',
    tagline: 'Ancient Pharaonic Wonders & Nile Majesty',
    description: 'Private historian access inside the Great Pyramids of Giza, the Grand Egyptian Museum treasures, and luxury Nile river cruises.',
    image: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 15,
    startingPrice: 79999,
    rating: 4.9,
    highlights: ['Great Pyramid & Sphinx Private Entry', 'Grand Egyptian Museum VIP Tour', 'Luxury Sunset Nile Felucca', 'Khan el-Khalili Bazaar'],
    weather: '18°C - 28°C (Pleasant Desert Winter)',
    bestTime: 'October to April',
  },
  {
    id: 'sydney',
    slug: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    region: 'Americas',
    tagline: 'Iconic Harbour, Sunlit Beaches & Blue Mountains',
    description: 'Private yachts beneath the Sydney Harbour Bridge, Opera House VIP lounge, Bondi coastal walks, and Blue Mountains eucalyptus valleys.',
    image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 13,
    startingPrice: 144999,
    rating: 4.9,
    highlights: ['Sydney Opera House Backstage Pass', 'Private Harbour Sunset Catamaran', 'Bondi to Coogee Coastal Walk', 'Blue Mountains Helicopter'],
    weather: '17°C - 26°C (Sunny Coastal Summer)',
    bestTime: 'October to April',
  },
  {
    id: 'singapore',
    slug: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    tagline: 'Garden City & Futuristic Luxury',
    description: 'Exclusive rooftop experiences atop Marina Bay Sands, supertree light shows in Gardens by the Bay, and Michelin Peranakan cuisine.',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=85',
    aspect: 'medium',
    toursCount: 17,
    startingPrice: 64999,
    rating: 4.9,
    highlights: ['Marina Bay Sands Infinity Pool', 'Gardens by the Bay Private Tour', 'Sentosa Yacht Charter', 'Peranakan Heritage Dining'],
    weather: '26°C - 32°C (Tropical Warmth)',
    bestTime: 'Year-Round / Nov to Jan',
  },
  {
    id: 'machupicchu',
    slug: 'machu-picchu',
    name: 'Machu Picchu',
    country: 'Peru',
    region: 'Americas',
    tagline: 'Lost Incan Citadel in the Andes',
    description: 'Scenic Hiram Bingham luxury train through cloud forests, private sunrise access to the ancient citadel, and Sacred Valley cultural immersion.',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 11,
    startingPrice: 189999,
    rating: 5.0,
    highlights: ['Hiram Bingham Belmond Luxury Train', 'Private Archaeologist Citadel Tour', 'Sacred Valley Weaving Villages', 'Cusco Colonial Palace Stay'],
    weather: '12°C - 20°C (Crisp Andean Air)',
    bestTime: 'May to October',
  },
  {
    id: 'queenstown',
    slug: 'queenstown',
    name: 'Queenstown',
    country: 'New Zealand',
    region: 'Americas',
    tagline: 'Alpine Fjords & Southern Lakes Majesty',
    description: 'Helicopter flights over Milford Sound cascading waterfalls, private lakefront lodges on Lake Wakatipu, and Central Otago pinot noir tastings.',
    image: 'https://images.unsplash.com/photo-1589802829985-817e51171b92?auto=format&fit=crop&w=1200&q=85',
    aspect: 'wide',
    toursCount: 14,
    startingPrice: 169999,
    rating: 5.0,
    highlights: ['Milford Sound Helicopter & Cruise', 'Lake Wakatipu Private Boat', 'Central Otago Boutique Vineyards', 'Dart River Wilderness Jet'],
    weather: '14°C - 23°C (Brisk Alpine Summer)',
    bestTime: 'December to March',
  },
  {
    id: 'kerala',
    slug: 'kerala',
    name: 'Kerala',
    country: 'India',
    region: 'Asia',
    tagline: "God's Own Country & Emerald Backwaters",
    description: 'Private luxury houseboats drifting through Alleppey palm lagoons, misty Munnar tea hills, and Ayurvedic wellness rejuvenation.',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 18,
    startingPrice: 22999,
    rating: 4.9,
    highlights: ['Alleppey Private Houseboat Cruise', 'Munnar Tea Plantation Walk', 'Periyar Wildlife Sanctuary', 'Authentic Ayurveda Retreat'],
    weather: '23°C - 30°C (Lush Tropical)',
    bestTime: 'September to March',
  },
  {
    id: 'goa',
    slug: 'goa',
    name: 'Goa',
    country: 'India',
    region: 'Islands',
    tagline: 'Portuguese Heritage & Sun-Kissed Coasts',
    description: 'Private sunset catamarans on the Arabian Sea, private heritage Portuguese mansions in Fontainhas, and secluded South Goa beaches.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=85',
    aspect: 'medium',
    toursCount: 22,
    startingPrice: 16999,
    rating: 4.8,
    highlights: ['Private Sunset Catamaran Charter', 'Fontainhas Heritage Walk', 'Dudhsagar Waterfalls Jeep Tour', 'South Goa Private Beach Cabana'],
    weather: '24°C - 32°C (Sunny Beach Weather)',
    bestTime: 'October to April',
  },
  {
    id: 'varanasi',
    slug: 'varanasi',
    name: 'Varanasi',
    country: 'India',
    region: 'Asia',
    tagline: 'Timeless Spiritual Ghats of the Ganga',
    description: 'Dawn wooden boat cruises on the sacred Ganga, grand evening Maha Aarti ceremonies at Dashashwamedh Ghat, and ancient silk weaving ateliers.',
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 14,
    startingPrice: 14999,
    rating: 4.9,
    highlights: ['Private Sunrise Ganga Boat Ritual', 'Exclusive Evening Ganga Aarti View', 'Sarnath Buddhist Heritage Tour', 'Banarasi Silk Master Weaver Atelier'],
    weather: '15°C - 28°C (Pleasant Autumn/Winter)',
    bestTime: 'October to March',
  },
  {
    id: 'andaman',
    slug: 'andaman-islands',
    name: 'Andaman & Nicobar',
    country: 'India',
    region: 'Islands',
    tagline: 'Turquoise Waters & Radhanagar Sands',
    description: 'Pristine coral diving in Havelock Island, bioluminescent night kayaking, and private secluded white sand coves in Neil Island.',
    image: 'https://images.unsplash.com/photo-1589136777351-fdc9c9cab193?auto=format&fit=crop&w=1200&q=85',
    aspect: 'wide',
    toursCount: 16,
    startingPrice: 36999,
    rating: 5.0,
    highlights: ['Havelock Scuba & Coral Reef Dive', 'Radhanagar Sunset Walk', 'Elephant Beach Snorkel Excursion', 'Night Bioluminescent Kayaking'],
    weather: '24°C - 30°C (Island Tropical)',
    bestTime: 'October to May',
  },
  {
    id: 'himachal',
    slug: 'himachal-manali',
    name: 'Himachal & Manali',
    country: 'India',
    region: 'Asia',
    tagline: 'Snow Pines, Rohtang Pass & Spiti Vistas',
    description: 'Snow-covered Himalayan ranges, pine-scented luxury chalets in Old Manali, thrilling Solang Valley paragliding, and Spiti lunar valleys.',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 20,
    startingPrice: 19999,
    rating: 4.9,
    highlights: ['Atal Tunnel & Sissu Glacial Valley', 'Solang Paragliding Excursion', 'Hadimba Temple & Old Manali Cafes', 'Kasol & Parvati River Trail'],
    weather: '5°C - 20°C (Alpine Chill)',
    bestTime: 'April to June & Dec to Feb (Snow)',
  },
  {
    id: 'meghalaya',
    slug: 'meghalaya',
    name: 'Meghalaya',
    country: 'India',
    region: 'Asia',
    tagline: 'Living Root Bridges & Crystal Dawki River',
    description: 'Walk ancient double-decker bio-engineered root bridges in Cherrapunji, boat on the crystal-clear glass waters of Dawki, and explore misty waterfalls.',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=85',
    aspect: 'medium',
    toursCount: 12,
    startingPrice: 26999,
    rating: 4.9,
    highlights: ['Double Decker Living Root Bridge Trek', 'Dawki Transparent River Boating', 'Nohkalikai Waterfall Cliff View', 'Mawlynnong Cleanest Village Tour'],
    weather: '12°C - 22°C (Misty Rainforest)',
    bestTime: 'September to May',
  },
  {
    id: 'agra',
    slug: 'agra-taj-mahal',
    name: 'Agra & Taj Heritage',
    country: 'India',
    region: 'Asia',
    tagline: 'Mughal Imperial Splendour & Marble Monument',
    description: 'Private sunrise historian tour of the Taj Mahal, VIP access to Agra Fort royal balconies, and 5-star Oberoi luxury palace dining.',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 14,
    startingPrice: 12999,
    rating: 4.9,
    highlights: ['Taj Mahal Private Sunrise Tour', 'Agra Fort Mughal Court View', 'Mehtab Bagh Sunset Silhouette', 'Fatehpur Sikri Royal Guided Walk'],
    weather: '16°C - 28°C (Pleasant Winter)',
    bestTime: 'October to March',
  },
  {
    id: 'rishikesh',
    slug: 'rishikesh-haridwar',
    name: 'Rishikesh & Ganga',
    country: 'India',
    region: 'Asia',
    tagline: 'Yoga Capital & White-Water Glaciers',
    description: 'Holistic wellness retreats on the banks of the emerald Ganga, thrilling grade IV white-water rafting, and Parmarth Niketan evening Aarti.',
    image: 'https://images.unsplash.com/photo-1506461883276-594a12b11cf3?auto=format&fit=crop&w=1200&q=85',
    aspect: 'medium',
    toursCount: 15,
    startingPrice: 15999,
    rating: 4.8,
    highlights: ['Shivpuri White-Water River Rafting', 'Parmarth Niketan Sunset Ganga Aarti', 'Beatles Ashram Heritage Walk', 'Luxury Riverside Glamping'],
    weather: '14°C - 26°C (Breezy Mountain River)',
    bestTime: 'September to June',
  },
  {
    id: 'ranthambore',
    slug: 'ranthambore-safari',
    name: 'Ranthambore',
    country: 'India',
    region: 'Asia',
    tagline: 'Royal Bengal Tiger Jungle Expeditions',
    description: 'Exclusive 4x4 open-top gypsy safaris in tiger territory, ancient 10th-century jungle fortresses, and luxury colonial tented glamping.',
    image: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=85',
    aspect: 'wide',
    toursCount: 11,
    startingPrice: 21999,
    rating: 5.0,
    highlights: ['Private 4x4 Gypsy Tiger Safari', 'Ranthambore Clifftop Fortress Tour', 'Luxury Starlit Forest Dinner', 'Birdwatching at Padam Lake'],
    weather: '15°C - 29°C (Dry Forest Sun)',
    bestTime: 'October to June',
  },
  {
    id: 'hampi',
    slug: 'hampi-ruins',
    name: 'Hampi',
    country: 'India',
    region: 'Asia',
    tagline: 'UNESCO Boulders & Vijayanagara Palaces',
    description: 'Marvel at stone chariots, ancient temple monoliths, coracle boat rides across the Tungabhadra river, and golden boulder sunsets.',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 10,
    startingPrice: 17999,
    rating: 4.8,
    highlights: ['Virupaksha Temple Monolith Tour', 'Vittala Temple Stone Chariot', 'Tungabhadra Coracle Boat Ride', 'Matanga Hill Sunset Panorama'],
    weather: '20°C - 32°C (Pleasant Winter)',
    bestTime: 'October to March',
  },
  {
    id: 'coorg',
    slug: 'coorg-coffee-hills',
    name: 'Coorg',
    country: 'India',
    region: 'Asia',
    tagline: 'Scotland of India & Mist Coffee Valleys',
    description: 'Fragrant Arabica coffee estates, cascading Abbey waterfalls, Tibetan settlements in Bylakuppe, and misty mountain viewpoints.',
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=85',
    aspect: 'medium',
    toursCount: 13,
    startingPrice: 16999,
    rating: 4.9,
    highlights: ['Private Coffee Plantation Masterclass', 'Abbey & Iruppu Waterfalls Excursion', 'Bylakuppe Golden Temple Stupa', 'Raja’s Seat Sunset Valley'],
    weather: '15°C - 24°C (Mist Hill Breezes)',
    bestTime: 'October to May',
  },
  {
    id: 'sikkim',
    slug: 'sikkim-gangtok',
    name: 'Sikkim & Gangtok',
    country: 'India',
    region: 'Asia',
    tagline: 'Sacred Himalayan Peaks & Monasteries',
    description: 'Panoramic sunrises over Mount Kanchenjunga, high-altitude turquoise Tsomgo Lake at 12,400 ft, and Rumtek Tibetan monastery chants.',
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 14,
    startingPrice: 25999,
    rating: 4.9,
    highlights: ['Tsomgo Lake & Nathu La Pass (14,140 ft)', 'Rumtek Monastery Chants Tour', 'Kanchenjunga Sunrise Viewpoint', 'Pelling Skywalk & Rabdentse Ruins'],
    weather: '8°C - 18°C (Crisp Mountain Breeze)',
    bestTime: 'March to May & Oct to Dec',
  },
  {
    id: 'nepal',
    slug: 'nepal-himalayas',
    name: 'Nepal',
    country: 'Nepal',
    region: 'Asia',
    tagline: 'Everest Vistas, Ancient Stupas & Pokhara Lakes',
    description: 'Mountain flights with up-close views of Mount Everest, serene boat rides on Pokhara Phewa Lake, and sacred Pashupatinath & Boudhanath stupas.',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=85',
    aspect: 'tall',
    toursCount: 16,
    startingPrice: 39999,
    rating: 5.0,
    highlights: ['Mount Everest Scenic Panoramic Flight', 'Boudhanath & Swayambhunath Stupas', 'Pokhara Phewa Lake Boat Cruise', 'Sarangkot Annapurna Sunrise'],
    weather: '10°C - 22°C (Clear Mountain Skies)',
    bestTime: 'September to November & March to May',
  },
  {
    id: 'srilanka',
    slug: 'sri-lanka',
    name: 'Sri Lanka',
    country: 'Sri Lanka',
    region: 'Islands',
    tagline: 'Lion Rock Sigiriya, Tea Hills & Whales',
    description: 'Ascend the 5th-century Sigiriya clifftop fortress, ride the iconic blue train through Ella tea hills, and spot blue whales off Mirissa coast.',
    image: 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=85',
    aspect: 'wide',
    toursCount: 15,
    startingPrice: 42999,
    rating: 4.9,
    highlights: ['Sigiriya Lion Rock Fortress Climb', 'Scenic Blue Train to Ella Tea Hills', 'Mirissa Blue Whale Watching Cruise', 'Yala National Park Leopard Safari'],
    weather: '24°C - 31°C (Tropical Island Warmth)',
    bestTime: 'December to April',
  },
]

export const TOURS = [
  {
    id: 'kashmir-escape',
    slug: 'kashmir-escape',
    title: 'Kashmir Escape',
    subtitle: 'Alpine Tranquility & Shikara Dreams',
    destination: 'Kashmir',
    destinationSlug: 'kashmir',
    duration: '7 Days / 6 Nights',
    days: 7,
    rating: 4.9,
    reviewsCount: 142,
    startingPrice: 24999,
    groupSize: 'Max 10 Explorers',
    image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1000&q=85',
    category: 'Adventure & Nature',
    overview: 'Escape into the pristine valleys of Kashmir. Wake up to misty mountain views on a private heritage houseboat in Srinagar, take thrilling gondola rides in Gulmarg, and trek through fragrant pine meadows in Pahalgam.',
    itinerary: [
      { day: 1, title: 'Arrival in Srinagar & Dal Lake Sunset Shikara', desc: 'Private airport transfer, check-in to a luxury Cedarwood Houseboat, followed by an evening shikara cruise across floating gardens.' },
      { day: 2, title: 'Old City Heritage & Mughal Gardens', desc: 'Explore Nishat and Shalimar Bagh, followed by artisan Pashmina weaving workshops and Kashmiri Wazwan banquet.' },
      { day: 3, title: 'Srinagar to Gulmarg Meadow of Flowers', desc: 'Scenic mountain drive to Gulmarg. Check into alpine pine chalet with panoramic views of Apharwat peak.' },
      { day: 4, title: 'Gulmarg Gondola Phase II & Snowline Exploration', desc: 'World’s highest cable car ride to 13,780 ft with panoramic views of Nanga Parbat and optional skiing/snowshoeing.' },
      { day: 5, title: 'Gulmarg to Pahalgam Valley of Shepherds', desc: 'Traverse saffron fields in Pampore and apple orchards before reaching the crystal-clear Lidder River in Pahalgam.' },
      { day: 6, title: 'Betaab Valley, Aru Valley & Pine Forest Trails', desc: 'Equestrian pony trail or private 4x4 excursion to tranquil alpine meadows surrounded by snow peaks.' },
      { day: 7, title: 'Farewell Kashmir & Return Departure', desc: 'Morning herbal Kahwa tea, souvenir boutique stop, and private luxury chauffeur transfer to Srinagar Airport.' },
    ],
    inclusions: [
      '6 nights luxury boutique & heritage houseboat accommodation',
      'Private chauffeured luxury SUV throughout the journey',
      'Daily gourmet artisan breakfast and gourmet dinners',
      'Gulmarg Gondola Phase 1 & 2 tickets included',
      'Private sunset Dal Lake Shikara ride',
      '24/7 dedicated local expedition concierge',
    ],
    exclusions: ['International & domestic airfare', 'Personal travel insurance', 'Discretionary gratuities'],
  },
  {
    id: 'maldives-retreat',
    slug: 'maldives-retreat',
    title: 'Maldives Retreat',
    subtitle: 'Ultra-Luxury Overwater Solitude',
    destination: 'Maldives',
    destinationSlug: 'maldives',
    duration: '5 Days / 4 Nights',
    days: 5,
    rating: 5.0,
    reviewsCount: 215,
    startingPrice: 84999,
    groupSize: 'Couples / Private',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1000&q=85',
    category: 'Luxury & Beach',
    overview: 'Experience the ultimate tropical paradise in a private overwater villa perched directly above transparent turquoise waters with private infinity pool and underwater coral reef access.',
    itinerary: [
      { day: 1, title: 'Seaplane Arrival & Villa Check-in', desc: 'Scenic seaplane transfer over coral atolls. Welcome champagne and check-in to your private sunrise overwater villa.' },
      { day: 2, title: 'Guided Coral Reef Snorkel & Marine Biology Tour', desc: 'Discover vibrant sea turtles, harmless reef sharks, and colorful corals with a certified resident marine biologist.' },
      { day: 3, title: 'Private Sandbank Picnic & Sunset Dolphin Cruise', desc: 'Cast away on an isolated white sandbank for a gourmet lunch, followed by an evening catamaran cruise spotting spinner dolphins.' },
      { day: 4, title: 'Overwater Spa Ritual & Floating Breakfast', desc: 'Morning floating breakfast in your private plunge pool, followed by an afternoon holistic Ayurvedic spa treatment.' },
      { day: 5, title: 'Farewell Seaplane & Departure', desc: 'Final morning swim in the lagoon, private seaplane transfer to Velana International Airport.' },
    ],
    inclusions: [
      '4 nights in an ultra-luxury Overwater Pool Villa',
      'Round-trip scenic seaplane transfers from Malé',
      'All-inclusive gourmet dining & sommelier wine selection',
      'Private Sandbank Robinson Crusoe experience',
      'Complimentary non-motorized water sports & snorkel gear',
    ],
    exclusions: ['International flights', 'Motorized watersports', 'Premium cellar vintage reserves'],
  },
  {
    id: 'dubai-explorer',
    slug: 'dubai-explorer',
    title: 'Dubai Explorer',
    subtitle: 'Modern Marvels & Arabian Dune Glamour',
    destination: 'Dubai',
    destinationSlug: 'dubai',
    duration: '6 Days / 5 Nights',
    days: 6,
    rating: 4.8,
    reviewsCount: 178,
    startingPrice: 48999,
    groupSize: 'Max 12 Explorers',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1000&q=85',
    category: 'Urban & Adventure',
    overview: 'From iconic architectural sky-rises to starlit luxury desert camps, immerse in the dazzling fusion of futuristic ambition and Bedouin heritage.',
    itinerary: [
      { day: 1, title: 'Arrival & Marina Yacht Welcome', desc: 'Chauffeured transfer to 5-star hotel in Downtown Dubai. Sunset yacht cruise around Dubai Marina and Ain Dubai.' },
      { day: 2, title: 'Burj Khalifa Sky & Museum of the Future', desc: 'VIP access to Burj Khalifa Level 148 At The Top Sky followed by an immersive journey into the Museum of the Future.' },
      { day: 3, title: 'Heritage Old Dubai & Spice Souks', desc: 'Traditional Abra boat crossing on Dubai Creek, Gold and Spice Souk tasting tour, and Al Fahidi historical quarter.' },
      { day: 4, title: 'Desert Conservation Reserve & Luxury Glamping', desc: 'Vintage Land Rover dune drive, royal falconry demonstration, starlit 5-course Bedouin dinner in private desert oasis.' },
      { day: 5, title: 'Palm Jumeirah & Atlantis Aquaventure / Skydiving', desc: 'Helicopter tour over The Palm, afternoon at leisure with beach club access or optional tandem skydive.' },
      { day: 6, title: 'Departure Chauffeur Transfer', desc: 'Boutique shopping at Dubai Mall and direct luxury transfer to DXB International Airport.' },
    ],
    inclusions: [
      '5 nights 5-star luxury hotel accommodation',
      'Private desert safari with royal falconry and starlit dinner',
      'VIP Burj Khalifa Sky fast-track entry',
      'Luxury private yacht sunset charter',
      'Private air-conditioned chauffeur throughout',
    ],
    exclusions: ['International flights', 'Optional tandem skydive fees', 'Visa processing'],
  },
  {
    id: 'rajasthan-heritage',
    slug: 'rajasthan-heritage',
    title: 'Rajasthan Heritage',
    subtitle: 'Grand Palaces, Fortresses & Thar Stargazing',
    destination: 'Rajasthan',
    destinationSlug: 'rajasthan',
    duration: '8 Days / 7 Nights',
    days: 8,
    rating: 4.9,
    reviewsCount: 164,
    startingPrice: 18999,
    groupSize: 'Max 8 Explorers',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1000&q=85',
    category: 'Culture & Heritage',
    overview: 'Walk the royal corridors of Rajput royalty across Jaipur, Jodhpur, and Udaipur. Stay in historic heritage palaces and sleep under the starry canopy of the Thar desert.',
    itinerary: [
      { day: 1, title: 'Jaipur The Pink City Welcome', desc: 'Arrival at Jaipur, check into a restored heritage palace hotel. Evening royal high tea.' },
      { day: 2, title: 'Amber Fort, City Palace & Hawa Mahal', desc: 'Private curated tour of Amber Fort with palace historian, observatory visit at Jantar Mantar, and artisan gemstone masterclass.' },
      { day: 3, title: 'Jaipur to Jodhpur Blue City', desc: 'Scenic journey through rural Rajasthan to Jodhpur. Check-in overlooking the massive Mehrangarh Fort.' },
      { day: 4, title: 'Mehrangarh Fortress & Thar Desert Camp', desc: 'Private fortress tour, followed by afternoon drive to luxury desert camp in Osian with camel safari at sunset.' },
      { day: 5, title: 'Jodhpur to Udaipur City of Lakes', desc: 'Drive through the Aravalli hills, visiting the intricately carved marble Ranakpur Jain Temples en route to Udaipur.' },
      { day: 6, title: 'Lake Pichola & Udaipur City Palace', desc: 'Private boat cruise on Lake Pichola with views of Lake Palace and Jag Mandir. Curated visit to Udaipur City Palace.' },
      { day: 7, title: 'Artisan Miniature Painting & Culinary Heritage', desc: 'Masterclass with master miniature painters followed by a royal Rajasthani cooking session with a noble family chef.' },
      { day: 8, title: 'Udaipur Departure', desc: 'Morning breakfast overlooking the lake and private chauffeur transfer to Udaipur Airport.' },
    ],
    inclusions: [
      '7 nights accommodation in heritage luxury palace properties',
      'All royal fort & palace entrance admissions with private historian guides',
      'Private Lake Pichola boat charter',
      'Luxury desert safari with folk music and candlelit dinner',
      'All breakfasts and 4 curated royal dinners',
    ],
    exclusions: ['Domestic/International airfare', 'Alcoholic beverages', 'Personal expenses'],
  },
  {
    id: 'kerala-serenade',
    slug: 'kerala',
    title: 'Kerala Backwaters Serenade',
    subtitle: 'Alleppey Cedar Houseboat & Munnar Tea Mists',
    destination: 'Kerala',
    destinationSlug: 'kerala',
    duration: '6 Days / 5 Nights',
    days: 6,
    rating: 4.9,
    reviewsCount: 198,
    startingPrice: 22999,
    groupSize: 'Max 8 Explorers',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1000&q=85',
    category: 'Wellness & Nature',
    overview: 'Drift through serene palm-fringed backwaters of Alleppey in a private luxury houseboat and wake up to the cool emerald mist of Munnar tea hills.',
    itinerary: [
      { day: 1, title: 'Cochin Arrival & Heritage Fort Kochi', desc: 'Private transfer to luxury heritage hotel, Chinese fishing nets sunset walk, and Kathakali cultural show.' },
      { day: 2, title: 'Cochin to Munnar Hill Station', desc: 'Scenic mountain drive passing Cheeyappara waterfalls to Munnar. Check into hillside tea boutique chalet.' },
      { day: 3, title: 'Munnar Tea Estate Trails & Eravikulam', desc: 'Private tea picking experience with estate manager and Nilgiri Tahr wildlife sanctuary safari.' },
      { day: 4, title: 'Munnar to Alleppey Houseboat Boarding', desc: 'Embark on a traditional luxury Kerala houseboat with dedicated chef, private deck, and sunset village cruising.' },
      { day: 5, title: 'Kumarakom Bird Sanctuary & Ayurvedic Rejuvenation', desc: 'Disembark and check into a lagoon resort for authentic herbal Ayurvedic wellness therapy.' },
      { day: 6, title: 'Departure Chauffeur Transfer', desc: 'Morning breakfast overlooking Lake Vembanad and transfer to Cochin International Airport.' },
    ],
    inclusions: ['5 nights luxury stay including private houseboat', 'All gourmet Kerala meals on houseboat', 'Daily breakfasts', 'Private chauffeur SUV'],
    exclusions: ['Flights', 'Personal Ayurveda treatments', 'Gratuities'],
  },
  {
    id: 'goa-coastal',
    slug: 'goa',
    title: 'Goa Coastal Luxury',
    subtitle: 'Private Sunset Catamaran & Portuguese Mansions',
    destination: 'Goa',
    destinationSlug: 'goa',
    duration: '5 Days / 4 Nights',
    days: 5,
    rating: 4.8,
    reviewsCount: 154,
    startingPrice: 16999,
    groupSize: 'Couples / Private',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=85',
    category: 'Luxury & Beach',
    overview: 'Experience the private luxury side of Goa with private Arabian Sea yacht charters, Latin Quarter heritage heritage walks, and secluded South Goa beaches.',
    itinerary: [
      { day: 1, title: 'Goa Arrival & Private Villa Check-in', desc: 'Chauffeured arrival at luxury beachfront resort in South Goa. Welcome cocktails and beach sunset.' },
      { day: 2, title: 'Fontainhas Latin Quarter & Spice Plantation', desc: 'Architectural walking tour of colorful Portuguese heritage homes followed by authentic Goan culinary lunch.' },
      { day: 3, title: 'Private Sunset Catamaran Sailing', desc: 'Charter a luxury catamaran on the Arabian Sea with champagne, dolphin spotting, and onboard DJ/chef.' },
      { day: 4, title: 'Secluded South Goa Coves & Beach Cabana', desc: 'Day at leisure in private beach cabana with complimentary water sports and oceanfront seafood dinner.' },
      { day: 5, title: 'Departure Transfer', desc: 'Morning swim, boutique souvenir shopping, and transfer to Goa Dabolim/MOPA Airport.' },
    ],
    inclusions: ['4 nights 5-star beachfront resort', 'Private sunset yacht charter with drinks', 'All luxury transfers', 'Daily artisan breakfasts'],
    exclusions: ['Airfare', 'Alcohol not specified', 'Personal watersports'],
  },
  {
    id: 'swiss-alpine',
    slug: 'switzerland',
    title: 'Swiss Alpine Odyssey',
    subtitle: 'Glacier Express Trains & Matterhorn Chalets',
    destination: 'Switzerland',
    destinationSlug: 'switzerland',
    duration: '8 Days / 7 Nights',
    days: 8,
    rating: 5.0,
    reviewsCount: 189,
    startingPrice: 149999,
    groupSize: 'Max 10 Explorers',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1000&q=85',
    category: 'Mountain & Luxury',
    overview: 'Ride the legendary Glacier Express First Class across snowy alpine peaks, stay in luxury pine chalets in Zermatt facing the Matterhorn, and cruise Lake Geneva.',
    itinerary: [
      { day: 1, title: 'Zurich Arrival & Lucerne Lakeside', desc: 'First class rail transfer to Lucerne. Private sunset yacht cruise on Lake Lucerne.' },
      { day: 2, title: 'Mount Pilatus Golden Roundtrip', desc: 'World’s steepest cogwheel railway to Mount Pilatus summit followed by aerial cableway.' },
      { day: 3, title: 'Glacier Express Panoramic Journey to Zermatt', desc: '8-hour panoramic First Class rail ride through 91 tunnels and across 291 bridges.' },
      { day: 4, title: 'Gornergrat & Matterhorn Sunrise', desc: 'Ascend to 10,135 ft for dramatic panoramic views of the Matterhorn and Monte Rosa massif.' },
      { day: 5, title: 'Zermatt to Interlaken & Jungfraujoch', desc: 'Journey to the Top of Europe at Jungfraujoch (11,333 ft) and explore the Ice Palace.' },
      { day: 6, title: 'Lauterbrunnen Valley of 72 Waterfalls', desc: 'Private e-bike tour through glacial valleys and Trümmelbach roaring waterfalls.' },
      { day: 7, title: 'Interlaken to Geneva Lakeside', desc: 'Scenic GoldenPass Express train to Montreux and Geneva with Swiss fondue dinner.' },
      { day: 8, title: 'Geneva Departure', desc: 'Morning chocolate masterclass and private transfer to Geneva International Airport.' },
    ],
    inclusions: ['Swiss First Class Travel Pass', '7 nights luxury 5-star Swiss chalet hotels', 'Glacier Express Excellence Class seats', 'All mountain excursion admissions'],
    exclusions: ['International flights', 'Personal ski rental', 'Travel insurance'],
  },
  {
    id: 'paris-haute',
    slug: 'paris',
    title: 'Parisian Haute Romance',
    subtitle: 'Private Louvre After-Hours & Seine River Dining',
    destination: 'Paris',
    destinationSlug: 'paris',
    duration: '6 Days / 5 Nights',
    days: 6,
    rating: 4.9,
    reviewsCount: 230,
    startingPrice: 124999,
    groupSize: 'Couples / Private',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=85',
    category: 'Romance & Culture',
    overview: 'Unlock private VIP access to the world’s greatest art galleries, dine aboard a glass-encased Michelin-star Seine boat, and savor Parisian haute elegance.',
    itinerary: [
      { day: 1, title: 'Paris Welcome & Luxury Chauffeur', desc: 'Private vintage car transfer from CDG to 5-star hotel near Place Vendôme. Welcome champagne.' },
      { day: 2, title: 'VIP Louvre After-Hours & Palais Royal', desc: 'Private guided tour of the Mona Lisa and Venus de Milo without public crowds.' },
      { day: 3, title: 'Montmartre Atelier Walks & Eiffel Tower Summit', desc: 'Artisan walking tour of artist studios in Montmartre, followed by VIP fast-track Eiffel Tower champagne experience.' },
      { day: 4, title: 'Palace of Versailles Private Royal Apartments', desc: 'Exclusive access to King Louis XIV private chambers and Hall of Mirrors with palace historian.' },
      { day: 5, title: 'Gourmet Seine Dinner Cruise', desc: '5-course Michelin-curated gastronomy cruise sailing past illuminated Parisian landmarks.' },
      { day: 6, title: 'Haute Shopping & Departure', desc: 'Private stylist session at Galeries Lafayette and direct luxury transfer to CDG Airport.' },
    ],
    inclusions: ['5 nights 5-star Paris hotel', 'Private Louvre & Versailles VIP tickets', 'Seine Michelin gourmet dinner cruise', 'Private chauffeur throughout'],
    exclusions: ['International flights', 'Personal purchases', 'Visa fees'],
  },
  {
    id: 'bali-sanctuary',
    slug: 'bali',
    title: 'Bali Island Sanctuary',
    subtitle: 'Ubud Rainforest Pool Villas & Cliffside Temples',
    destination: 'Bali',
    destinationSlug: 'bali',
    duration: '7 Days / 6 Nights',
    days: 7,
    rating: 4.9,
    reviewsCount: 210,
    startingPrice: 38999,
    groupSize: 'Couples / Small Group',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1000&q=85',
    category: 'Wellness & Nature',
    overview: 'Stay in private jungle pool villas overlooking Ubud emerald valleys, take sunrise volcano treks, and unwind with traditional Balinese flower spa therapies.',
    itinerary: [
      { day: 1, title: 'Denpasar Arrival to Ubud Jungle', desc: 'Private transfer to ultra-luxury valley pool villa in Ubud. Welcome flower blessing ceremony.' },
      { day: 2, title: 'Tegalalang Rice Terraces & Sacred Water Temple', desc: 'Morning walk in emerald rice terraces and purification ritual at Tirta Empul.' },
      { day: 3, title: 'Mount Batur Sunrise Jeep Safari', desc: '4x4 sunrise drive across black volcanic lava fields with hot springs bath.' },
      { day: 4, title: 'Ubud to Nusa Dua Oceanfront Resort', desc: 'Transfer to clifftop ocean resort with private beach and infinity pool.' },
      { day: 5, title: 'Nusa Penida Island Private Speedboat', desc: 'Explore Kelingking T-Rex cliff, Angel’s Billabong, and swim with giant Manta Rays.' },
      { day: 6, title: 'Uluwatu Sunset Temple & Kecak Fire Dance', desc: 'Clifftop sunset temple view followed by traditional Kecak dance and Jimbaran seafood dinner.' },
      { day: 7, title: 'Balinese Spa Ritual & Departure', desc: '2-hour traditional Balinese body massage and private transfer to Denpasar Airport.' },
    ],
    inclusions: ['6 nights pool villa & 5-star beach resort', 'Mount Batur 4x4 sunrise safari', 'Nusa Penida private speedboat tour', 'All airport and inter-hotel transfers'],
    exclusions: ['International airfare', 'Personal expenses', 'Visa on arrival'],
  },
  {
    id: 'tokyo-kyoto',
    slug: 'tokyo',
    title: 'Tokyo & Kyoto Zen Odyssey',
    subtitle: 'Shinkansen Bullet Train & Geisha Tea Ceremony',
    destination: 'Tokyo',
    destinationSlug: 'tokyo',
    duration: '9 Days / 8 Nights',
    days: 9,
    rating: 4.9,
    reviewsCount: 175,
    startingPrice: 134999,
    groupSize: 'Max 10 Explorers',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1000&q=85',
    category: 'Culture & Heritage',
    overview: 'Experience the ultimate fusion of futuristic neon metropolis in Tokyo and ancient bamboo zen shrines in Kyoto with First-Class Shinkansen bullet train transit.',
    itinerary: [
      { day: 1, title: 'Tokyo Arrival & Shinjuku Neon Night', desc: 'Private transfer to 5-star hotel in Ginza. Evening cocktail tour overlooking Shibuya crossing.' },
      { day: 2, title: 'Asakusa Senso-ji & TeamLab Borderless', desc: 'Ancient temple tour followed by immersive digital art museum experience.' },
      { day: 3, title: 'Mount Fuji & Hakone Onsen Day Excursion', desc: 'Scenic private tour to Mount Fuji 5th station and Lake Ashi pirate boat cruise with hot spring onsen.' },
      { day: 4, title: 'Shinkansen Bullet Train to Kyoto', desc: 'First Class Gran Class bullet train to ancient capital Kyoto. Check into luxury Ryokan.' },
      { day: 5, title: 'Fushimi Inari 10,000 Gates & Kinkaku-ji', desc: 'Sunrise hike through thousands of vermilion Torii gates and the Golden Pavilion.' },
      { day: 6, title: 'Arashiyama Bamboo Grove & Private Tea Ceremony', desc: 'Walk through whispering bamboo trails and attend private matcha ceremony with tea master.' },
      { day: 7, title: 'Nara Deer Park & Todai-ji Giant Buddha', desc: 'Day excursion to feed sacred bowing deer and visit world’s largest bronze Buddha.' },
      { day: 8, title: 'Gion Geisha District Evening Kaiseki Banquet', desc: 'Curated walk through preserved wooden tea house alleys with authentic 9-course Kaiseki dinner.' },
      { day: 9, title: 'Osaka/Tokyo Return Departure', desc: 'Bullet train transfer to Kansai or Haneda International Airport.' },
    ],
    inclusions: ['7-Day Japan Rail Pass', '8 nights luxury hotel & authentic Ryokan', 'Private tea ceremony & Kaiseki dinner', 'All tour guide admissions'],
    exclusions: ['International flights', 'Personal shopping', 'Travel insurance'],
  },
  {
    id: 'santorini-caldera',
    slug: 'santorini',
    title: 'Santorini Sunset & Caldera',
    subtitle: 'Cliffside Infinity Pool & Private Catamaran',
    destination: 'Santorini',
    destinationSlug: 'santorini',
    duration: '6 Days / 5 Nights',
    days: 6,
    rating: 5.0,
    reviewsCount: 168,
    startingPrice: 119999,
    groupSize: 'Couples / Private',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1000&q=85',
    category: 'Luxury & Beach',
    overview: 'Stay in whitewashed cliffside cave suites in Oia with private plunge pools facing the azure Aegean caldera, and sail on sunset catamarans.',
    itinerary: [
      { day: 1, title: 'Santorini Arrival & Oia Cave Suite Check-in', desc: 'Chauffeured transfer to clifftop boutique suite in Oia. Welcome volcanic Greek wine.' },
      { day: 2, title: 'Fira to Oia Clifftop Scenic Hike', desc: 'Panoramic walk along the caldera edge with endless Aegean blue views.' },
      { day: 3, title: 'Private Sunset Catamaran Cruise', desc: 'Sail past Red Beach, White Beach, and swim in volcanic hot springs with onboard Greek barbecue.' },
      { day: 4, title: 'Akrotiri Prehistoric Ruins & Volcanic Winery', desc: 'Private archaeologist tour of Bronze Age ruins and tasting 5 volcanic Assyrtiko wines.' },
      { day: 5, title: 'Day at Leisure & Oia Sunset Dinner', desc: 'Relax at your private infinity pool followed by a candlelit clifftop cliff dinner in Ammoudi Bay.' },
      { day: 6, title: 'Departure Chauffeur Transfer', desc: 'Morning Greek yogurt breakfast and private transfer to Santorini Airport or Port.' },
    ],
    inclusions: ['5 nights luxury cliffside cave suite', 'Private sunset catamaran with meal & drinks', 'All private chauffeur transfers', 'Daily gourmet breakfasts'],
    exclusions: ['Airfare to Greece', 'Personal boat extras', 'Discretionary tips'],
  },
  {
    id: 'ladakh-highpass',
    slug: 'ladakh',
    title: 'Ladakh High-Pass Odyssey',
    subtitle: 'Pangong Tso Glamping & Nubra Camel Dunes',
    destination: 'Ladakh',
    destinationSlug: 'ladakh',
    duration: '7 Days / 6 Nights',
    days: 7,
    rating: 4.9,
    reviewsCount: 145,
    startingPrice: 32999,
    groupSize: 'Max 10 Explorers',
    image: 'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?auto=format&fit=crop&w=1000&q=85',
    category: 'Adventure & Nature',
    overview: 'Traverse the highest motorable passes in the world, sleep under millions of stars in luxury glamping tents by Pangong Lake, and ride Bactrian camels in Nubra.',
    itinerary: [
      { day: 1, title: 'Leh Arrival & High Altitude Acclimatization', desc: 'Scenic flight landing over snow peaks at Leh. Gentle rest and evening walk in Leh Main Bazaar.' },
      { day: 2, title: 'Hall of Fame, Magnetic Hill & Sangam Confluence', desc: 'Witness the turquoise confluence of Indus and Zanskar rivers and visit Gurudwara Pathar Sahib.' },
      { day: 3, title: 'Khardung La Pass (17,982 ft) to Nubra Valley', desc: 'Cross world-renowned Khardung La pass to Diskit Monastery and Hunder white sand dunes.' },
      { day: 4, title: 'Turtuk Border Village & Balti Culture', desc: 'Visit the last northern Indian village with apricot orchards and unique Indo-Aryan culture.' },
      { day: 5, title: 'Nubra to Pangong Tso Lake (14,270 ft)', desc: 'Scenic journey along Shyok river to dramatic Pangong Tso. Luxury lakefront glamping camp.' },
      { day: 6, title: 'Chang La Pass Return to Leh & Thiksey Sunrise', desc: 'Sunrise over turquoise lake, cross Chang La pass, and visit magnificent 12-storey Thiksey Monastery.' },
      { day: 7, title: 'Departure Chauffeur Transfer', desc: 'Early morning butter tea and private transfer to Kushok Bakula Rimpochee Airport.' },
    ],
    inclusions: ['6 nights accommodation including Pangong luxury camps', 'Private 4x4 SUV throughout', 'All Inner Line Permits & environmental fees', 'All breakfasts & dinners'],
    exclusions: ['Domestic flights to Leh', 'Personal oxygen kits if required', 'Camel ride fees'],
  },
  {
    id: 'iceland-aurora',
    slug: 'iceland',
    title: 'Iceland Northern Lights Safari',
    subtitle: 'Aurora Borealis Chase & Geothermal Blue Lagoon',
    destination: 'Iceland',
    destinationSlug: 'iceland',
    duration: '7 Days / 6 Nights',
    days: 7,
    rating: 5.0,
    reviewsCount: 132,
    startingPrice: 174999,
    groupSize: 'Max 8 Explorers',
    image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1000&q=85',
    category: 'Arctic Expeditions',
    overview: 'Chase the ethereal green dance of the Northern Lights across dark arctic skies, soak in mineral-rich geothermal lagoons, and hike inside crystalline blue ice caves.',
    itinerary: [
      { day: 1, title: 'Reykjavik Arrival & Blue Lagoon Retreat', desc: 'Chauffeured transfer to geothermal Blue Lagoon with Silica mask ritual. Check into luxury hotel in Reykjavik.' },
      { day: 2, title: 'Golden Circle & Thingvellir Rift Valley', desc: 'Gullfoss roaring waterfall, erupting Strokkur geyser, and walk between North American & Eurasian tectonic plates.' },
      { day: 3, title: 'South Coast Waterfalls & Black Sand Beach', desc: 'Walk behind Seljalandsfoss waterfall, Skógafoss, and Reynisfjara black basalt columns.' },
      { day: 4, title: 'Vatnajökull Glacier Crystal Ice Cave Expedition', desc: 'Super-jeep excursion to explore naturally formed iridescent blue ice caves inside Europe’s largest glacier.' },
      { day: 5, title: 'Jökulsárlón Glacier Lagoon & Diamond Beach', desc: 'Glistening icebergs floating to sea and washing up like crystals on black sands.' },
      { day: 6, title: 'Private Northern Lights Super-Jeep Chase', desc: 'Night expedition away from city lights with professional aurora photographer and hot cocoa.' },
      { day: 7, title: 'Reykjavik City Walk & Departure', desc: 'Harpa concert hall, Hallgrímskirkja church, and transfer to Keflavik Airport.' },
    ],
    inclusions: ['6 nights 4-star boutique Nordic hotels', 'Private Super-Jeep transport with guide', 'Blue Lagoon Premium entrance', 'Ice cave gear and entrance'],
    exclusions: ['International airfare', 'Alcoholic beverages', 'Winter cold-weather gear rental'],
  },
  {
    id: 'amalfi-glamour',
    slug: 'amalfi-coast',
    title: 'Amalfi Coast & Capri Glamour',
    subtitle: 'Positano Pastel Clifftops & Private Speedboat',
    destination: 'Amalfi Coast',
    destinationSlug: 'amalfi-coast',
    duration: '7 Days / 6 Nights',
    days: 7,
    rating: 4.9,
    reviewsCount: 156,
    startingPrice: 139999,
    groupSize: 'Couples / Private',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=85',
    category: 'Luxury & Beach',
    overview: 'Discover pastel Italian villages clinging to dramatic coastal cliffs, charter private vintage wooden speedboats around Capri, and dine overlooking the Tyrrhenian Sea.',
    itinerary: [
      { day: 1, title: 'Naples Arrival to Positano Clifftop Hotel', desc: 'Private luxury Mercedes transfer along the scenic Amalfi Drive. Welcome Limoncello on private sea balcony.' },
      { day: 2, title: 'Positano Boutiques & Beach Club Cabana', desc: 'Stroll cobblestone pastel lanes and relax at exclusive Spiaggia Grande beach club.' },
      { day: 3, title: 'Private Capri Island Yacht Charter', desc: 'Full-day Riva speedboat charter to Capri, Faraglioni rock arches, and swim in the Green Grotto.' },
      { day: 4, title: 'Ravello Clifftop Gardens & Villa Cimbrone', desc: 'Visit the Infinity Terrace in Ravello suspended 1,200 ft above the sea with classical music.' },
      { day: 5, title: 'Amalfi Town & Artisan Lemon Grove Tour', desc: 'Explore the 9th-century Amalfi Cathedral and attend masterclass with a generational Limoncello producer.' },
      { day: 6, title: 'Path of the Gods Hike or Clifftop Cooking Class', desc: 'Panoramic cliff hike or private cooking class preparing handmade pasta with a local Italian Nonna.' },
      { day: 7, title: 'Departure Chauffeur Transfer', desc: 'Final morning espresso with sea view and private transfer to Naples Airport or Train Station.' },
    ],
    inclusions: ['6 nights luxury clifftop sea-view hotel', 'Full-day private Capri yacht charter', 'All Mercedes chauffeur transfers', 'Daily gourmet Italian breakfasts'],
    exclusions: ['International flights', 'Capri Blue Grotto rowing boat fee', 'Personal shopping'],
  },
  {
    id: 'nepal-everest',
    slug: 'nepal-himalayas',
    title: 'Nepal Everest & Pokhara Vistas',
    subtitle: 'Scenic Everest Mountain Flight & Phewa Lake',
    destination: 'Nepal',
    destinationSlug: 'nepal',
    duration: '6 Days / 5 Nights',
    days: 6,
    rating: 5.0,
    reviewsCount: 140,
    startingPrice: 39999,
    groupSize: 'Max 10 Explorers',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=85',
    category: 'Mountain & Heritage',
    overview: 'Fly alongside Mount Everest at sunrise, explore sacred ancient Buddhist stupas in Kathmandu, and boat across tranquil Phewa Lake in Pokhara with Annapurna reflection.',
    itinerary: [
      { day: 1, title: 'Kathmandu Arrival & Heritage Dwarika’s Hotel', desc: 'Private transfer to museum-hotel Dwarika’s. Traditional Newari welcome dinner.' },
      { day: 2, title: 'Mount Everest Scenic Flight & Ancient Stupas', desc: 'Early morning panoramic flight with direct views of Mt. Everest (8,848m). Visit Boudhanath and Swayambhunath.' },
      { day: 3, title: 'Kathmandu to Pokhara Lake City Flight', desc: 'Short scenic flight to Pokhara. Check into lakeside resort facing the Annapurna range.' },
      { day: 4, title: 'Sarangkot Sunrise & Phewa Lake Boating', desc: 'Sunrise view of Machhapuchhre (Fishtail Peak) followed by private wooden boat cruise on Phewa Lake.' },
      { day: 5, title: 'Peace Pagoda & Tibetan Refugee Settlement', desc: 'Hike to World Peace Pagoda, visit Davis Falls, and artisan Tibetan carpet weaving workshops.' },
      { day: 6, title: 'Return Flight to Kathmandu & Departure', desc: 'Scenic flight to Kathmandu, souvenir shopping in Thamel, and international departure transfer.' },
    ],
    inclusions: ['Mount Everest scenic flight ticket', 'Internal domestic flights Kathmandu-Pokhara-Kathmandu', '5 nights luxury hotels', 'Private guides and entrance permits'],
    exclusions: ['International airfare', 'Nepal tourist visa', 'Personal travel insurance'],
  },
]

export const EXPERIENCES = [
  {
    number: '01',
    title: 'Himalayan Adventure',
    subtitle: 'High-altitude treks, glacial lakes & Tibetan monasteries',
    tag: 'Mountain Trekking',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    link: '/tours/kashmir-escape',
  },
  {
    number: '02',
    title: 'Luxury Beach Escape',
    subtitle: 'Private islands, overwater villas & pristine coral atolls',
    tag: 'Tropical Seclusion',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    link: '/tours/maldives-retreat',
  },
  {
    number: '03',
    title: 'Desert Experience',
    subtitle: 'Silk-road dunes, starry skies & royal Bedouin hospitality',
    tag: 'Desert Expeditions',
    image: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
    link: '/tours/dubai-explorer',
  },
  {
    number: '04',
    title: 'European Journey',
    subtitle: 'Timeless architecture, alpine passes & Michelin gastronomy',
    tag: 'Art & Heritage',
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80',
    link: '/destinations/paris',
  },
  {
    number: '05',
    title: 'Romantic Getaway',
    subtitle: 'Intimate retreats, sunset yachting & candlelight dining',
    tag: 'Couples & Honeymoon',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80',
    link: '/tours/maldives-retreat',
  },
  {
    number: '06',
    title: 'Family Vacation',
    subtitle: 'Immersive wildlife safaris, culture & customized multi-generational trips',
    tag: 'Curated Family Trips',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    link: '/custom-trip',
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Eleanor Vance',
    role: 'Architect & Explorer',
    location: 'London, United Kingdom',
    destination: 'Kashmir & Swiss Alps',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    review:
      'The journey to Kashmir curated by Tours & Travels was nothing short of poetic. Every detail—from the private sunrise shikara on Dal Lake to the hidden alpine chalet in Gulmarg—felt tailored with remarkable elegance. Unmatched craftsmanship in modern travel.',
  },
  {
    id: 2,
    name: 'Marcus & Sophia Lindqvist',
    role: 'Design Directors',
    location: 'Stockholm, Sweden',
    destination: 'Maldives Overwater Sanctuary',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    review:
      'We wanted complete seclusion without sacrificing aesthetic excellence. Tours & Travels delivered beyond our wildest imaginations. The private sandbank dinner at sunset was the highlight of our decade.',
  },
  {
    id: 3,
    name: 'Aarav Singhania',
    role: 'Entrepreneur',
    location: 'Singapore',
    destination: 'Royal Rajasthan Expedition',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    review:
      'The access they provided to private royal palace collections and exclusive dining with local historians made Rajasthan feel entirely fresh and profoundly luxurious. Outstanding service!',
  },
]

export const GALLERY_ITEMS = [
  {
    id: 1,
    title: 'Sonamarg Alpine Peaks & Valley',
    location: 'Sonamarg, Kashmir, India',
    heightClass: 'h-[200px] sm:h-[220px]',
    image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 2,
    title: 'Maldives Overwater Sanctuary',
    location: 'Baa Atoll, Maldives',
    heightClass: 'h-[260px] sm:h-[280px]',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 3,
    title: 'Ubud Tegallalang Rice Terraces',
    location: 'Bali, Indonesia',
    heightClass: 'h-[180px] sm:h-[200px]',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 4,
    title: 'Arabian Desert Golden Dunes',
    location: 'Dubai, UAE',
    heightClass: 'h-[240px] sm:h-[260px]',
    image: 'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 5,
    title: 'Eiffel Tower Sunset over Seine',
    location: 'Paris, France',
    heightClass: 'h-[270px] sm:h-[290px]',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 6,
    title: 'Hawa Mahal Palace of Winds',
    location: 'Jaipur, Rajasthan, India',
    heightClass: 'h-[190px] sm:h-[210px]',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 7,
    title: 'Mount Fuji & Cherry Blossoms',
    location: 'Tokyo / Fuji, Japan',
    heightClass: 'h-[250px] sm:h-[270px]',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 8,
    title: 'Santorini Blue Domes & Caldera',
    location: 'Oia, Santorini, Greece',
    heightClass: 'h-[200px] sm:h-[220px]',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 9,
    title: 'Matterhorn Alpine Reflection',
    location: 'Zermatt, Switzerland',
    heightClass: 'h-[260px] sm:h-[280px]',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 10,
    title: 'Positano Amalfi Cliffside Coast',
    location: 'Amalfi Coast, Italy',
    heightClass: 'h-[190px] sm:h-[210px]',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 11,
    title: 'Twelve Apostles Great Ocean Road',
    location: 'Victoria, Australia',
    heightClass: 'h-[270px] sm:h-[290px]',
    image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 12,
    title: 'Table Mountain Coastal Sunset',
    location: 'Cape Town, South Africa',
    heightClass: 'h-[210px] sm:h-[230px]',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=85',
  },
]
